/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Company,
  CompanyCreate,
  CompanyUpdate,
  GetCompaniesApiV1CompaniesGetParams,
  HTTPValidationError
} from '.././model';

import { customInstance } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a list of companies owned by the current user with pagination.

- **skip**: Number of records to skip (for pagination)
- **limit**: Maximum number of records to return (max 100)

Returns only companies belonging to the authenticated user.
 * @summary Get Companies
 */
export const getCompaniesApiV1CompaniesGet = (
    params?: GetCompaniesApiV1CompaniesGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Company[]>(
      {url: `/api/v1/companies/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetCompaniesApiV1CompaniesGetQueryKey = (params?: GetCompaniesApiV1CompaniesGetParams,) => {
    return [
    `/api/v1/companies/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCompaniesApiV1CompaniesGetQueryOptions = <TData = Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>, TError = HTTPValidationError>(params?: GetCompaniesApiV1CompaniesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompaniesApiV1CompaniesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>> = ({ signal }) => getCompaniesApiV1CompaniesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCompaniesApiV1CompaniesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>>
export type GetCompaniesApiV1CompaniesGetQueryError = HTTPValidationError


export function useGetCompaniesApiV1CompaniesGet<TData = Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>, TError = HTTPValidationError>(
 params: undefined |  GetCompaniesApiV1CompaniesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>,
          TError,
          Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompaniesApiV1CompaniesGet<TData = Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>, TError = HTTPValidationError>(
 params?: GetCompaniesApiV1CompaniesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>,
          TError,
          Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompaniesApiV1CompaniesGet<TData = Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>, TError = HTTPValidationError>(
 params?: GetCompaniesApiV1CompaniesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Companies
 */

export function useGetCompaniesApiV1CompaniesGet<TData = Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>, TError = HTTPValidationError>(
 params?: GetCompaniesApiV1CompaniesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompaniesApiV1CompaniesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCompaniesApiV1CompaniesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new company.

- **name**: Company name (required)
- **siret**: French business ID - 14 digits (optional)
- **website**: Company website URL (optional)
- **headquarters**: Company headquarters address (optional)
- **is_intermediary**: Whether this is an intermediary company like ESN or agency (default: false)
- **company_type**: Type of company: ESN, startup, enterprise, SME, etc. (optional)
- **industry**: Industry sector: Healthcare, automotive, technology, etc. (optional)
- **notes**: Additional notes (optional)

The company will be automatically assigned to the authenticated user.
 * @summary Create Company
 */
export const createCompanyApiV1CompaniesPost = (
    companyCreate: CompanyCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Company>(
      {url: `/api/v1/companies/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: companyCreate, signal
    },
      options);
    }
  


export const getCreateCompanyApiV1CompaniesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCompanyApiV1CompaniesPost>>, TError,{data: CompanyCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCompanyApiV1CompaniesPost>>, TError,{data: CompanyCreate}, TContext> => {

const mutationKey = ['createCompanyApiV1CompaniesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCompanyApiV1CompaniesPost>>, {data: CompanyCreate}> = (props) => {
          const {data} = props ?? {};

          return  createCompanyApiV1CompaniesPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCompanyApiV1CompaniesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCompanyApiV1CompaniesPost>>>
    export type CreateCompanyApiV1CompaniesPostMutationBody = CompanyCreate
    export type CreateCompanyApiV1CompaniesPostMutationError = HTTPValidationError

    /**
 * @summary Create Company
 */
export const useCreateCompanyApiV1CompaniesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCompanyApiV1CompaniesPost>>, TError,{data: CompanyCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCompanyApiV1CompaniesPost>>,
        TError,
        {data: CompanyCreate},
        TContext
      > => {

      const mutationOptions = getCreateCompanyApiV1CompaniesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a specific company by ID.

- **company_id**: The ID of the company to retrieve

Returns 404 if company doesn't exist or doesn't belong to the authenticated user.
 * @summary Get Company
 */
export const getCompanyApiV1CompaniesCompanyIdGet = (
    companyId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Company>(
      {url: `/api/v1/companies/${companyId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCompanyApiV1CompaniesCompanyIdGetQueryKey = (companyId?: number,) => {
    return [
    `/api/v1/companies/${companyId}`
    ] as const;
    }

    
export const getGetCompanyApiV1CompaniesCompanyIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>, TError = HTTPValidationError>(companyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompanyApiV1CompaniesCompanyIdGetQueryKey(companyId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>> = ({ signal }) => getCompanyApiV1CompaniesCompanyIdGet(companyId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(companyId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCompanyApiV1CompaniesCompanyIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>>
export type GetCompanyApiV1CompaniesCompanyIdGetQueryError = HTTPValidationError


export function useGetCompanyApiV1CompaniesCompanyIdGet<TData = Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>, TError = HTTPValidationError>(
 companyId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>,
          TError,
          Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompanyApiV1CompaniesCompanyIdGet<TData = Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>, TError = HTTPValidationError>(
 companyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>,
          TError,
          Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompanyApiV1CompaniesCompanyIdGet<TData = Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>, TError = HTTPValidationError>(
 companyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Company
 */

export function useGetCompanyApiV1CompaniesCompanyIdGet<TData = Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>, TError = HTTPValidationError>(
 companyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyApiV1CompaniesCompanyIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCompanyApiV1CompaniesCompanyIdGetQueryOptions(companyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing company.

- **company_id**: The ID of the company to update
- All fields are optional - only provided fields will be updated

Returns 404 if company doesn't exist or doesn't belong to the authenticated user.
 * @summary Update Company
 */
export const updateCompanyApiV1CompaniesCompanyIdPut = (
    companyId: number,
    companyUpdate: CompanyUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Company>(
      {url: `/api/v1/companies/${companyId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: companyUpdate
    },
      options);
    }
  


export const getUpdateCompanyApiV1CompaniesCompanyIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCompanyApiV1CompaniesCompanyIdPut>>, TError,{companyId: number;data: CompanyUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCompanyApiV1CompaniesCompanyIdPut>>, TError,{companyId: number;data: CompanyUpdate}, TContext> => {

const mutationKey = ['updateCompanyApiV1CompaniesCompanyIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCompanyApiV1CompaniesCompanyIdPut>>, {companyId: number;data: CompanyUpdate}> = (props) => {
          const {companyId,data} = props ?? {};

          return  updateCompanyApiV1CompaniesCompanyIdPut(companyId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCompanyApiV1CompaniesCompanyIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateCompanyApiV1CompaniesCompanyIdPut>>>
    export type UpdateCompanyApiV1CompaniesCompanyIdPutMutationBody = CompanyUpdate
    export type UpdateCompanyApiV1CompaniesCompanyIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Company
 */
export const useUpdateCompanyApiV1CompaniesCompanyIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCompanyApiV1CompaniesCompanyIdPut>>, TError,{companyId: number;data: CompanyUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCompanyApiV1CompaniesCompanyIdPut>>,
        TError,
        {companyId: number;data: CompanyUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateCompanyApiV1CompaniesCompanyIdPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a company.

- **company_id**: The ID of the company to delete

Note: This will cascade delete all associated products.
Opportunities and contacts will have their company_id set to NULL.

Returns 404 if company doesn't exist or doesn't belong to the authenticated user.
 * @summary Delete Company
 */
export const deleteCompanyApiV1CompaniesCompanyIdDelete = (
    companyId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/companies/${companyId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteCompanyApiV1CompaniesCompanyIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompanyApiV1CompaniesCompanyIdDelete>>, TError,{companyId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCompanyApiV1CompaniesCompanyIdDelete>>, TError,{companyId: number}, TContext> => {

const mutationKey = ['deleteCompanyApiV1CompaniesCompanyIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCompanyApiV1CompaniesCompanyIdDelete>>, {companyId: number}> = (props) => {
          const {companyId} = props ?? {};

          return  deleteCompanyApiV1CompaniesCompanyIdDelete(companyId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCompanyApiV1CompaniesCompanyIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCompanyApiV1CompaniesCompanyIdDelete>>>
    
    export type DeleteCompanyApiV1CompaniesCompanyIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Company
 */
export const useDeleteCompanyApiV1CompaniesCompanyIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompanyApiV1CompaniesCompanyIdDelete>>, TError,{companyId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCompanyApiV1CompaniesCompanyIdDelete>>,
        TError,
        {companyId: number},
        TContext
      > => {

      const mutationOptions = getDeleteCompanyApiV1CompaniesCompanyIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    