/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetOpportunityContactsApiV1OpportunityContactsGetParams,
  HTTPValidationError,
  OpportunityContact,
  OpportunityContactCreate,
  OpportunityContactUpdate
} from '.././model';

import { customInstance } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a list of opportunity-contact associations owned by the current user with pagination and filtering.

- **skip**: Number of records to skip (for pagination)
- **limit**: Maximum number of records to return (max 100)
- **opportunity_id**: Optional filter by opportunity ID
- **contact_id**: Optional filter by contact ID
- **is_primary_contact**: Optional filter by primary contact status

Returns only associations where the opportunity belongs to the authenticated user.
 * @summary Get Opportunity Contacts
 */
export const getOpportunityContactsApiV1OpportunityContactsGet = (
    params?: GetOpportunityContactsApiV1OpportunityContactsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OpportunityContact[]>(
      {url: `/api/v1/opportunity-contacts/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetOpportunityContactsApiV1OpportunityContactsGetQueryKey = (params?: GetOpportunityContactsApiV1OpportunityContactsGetParams,) => {
    return [
    `/api/v1/opportunity-contacts/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetOpportunityContactsApiV1OpportunityContactsGetQueryOptions = <TData = Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>, TError = HTTPValidationError>(params?: GetOpportunityContactsApiV1OpportunityContactsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOpportunityContactsApiV1OpportunityContactsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>> = ({ signal }) => getOpportunityContactsApiV1OpportunityContactsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOpportunityContactsApiV1OpportunityContactsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>>
export type GetOpportunityContactsApiV1OpportunityContactsGetQueryError = HTTPValidationError


export function useGetOpportunityContactsApiV1OpportunityContactsGet<TData = Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetOpportunityContactsApiV1OpportunityContactsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>,
          TError,
          Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpportunityContactsApiV1OpportunityContactsGet<TData = Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>, TError = HTTPValidationError>(
 params?: GetOpportunityContactsApiV1OpportunityContactsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>,
          TError,
          Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpportunityContactsApiV1OpportunityContactsGet<TData = Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>, TError = HTTPValidationError>(
 params?: GetOpportunityContactsApiV1OpportunityContactsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Opportunity Contacts
 */

export function useGetOpportunityContactsApiV1OpportunityContactsGet<TData = Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>, TError = HTTPValidationError>(
 params?: GetOpportunityContactsApiV1OpportunityContactsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityContactsApiV1OpportunityContactsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOpportunityContactsApiV1OpportunityContactsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new link between an opportunity and a contact.

- **opportunity_id**: ID of the opportunity (required)
- **contact_id**: ID of the contact (required)
- **is_primary_contact**: Primary contact flag (default: false)
- **contact_role**: Role description (optional)
- **origin**: How contact is related (optional)
- **notes**: Contextual notes (optional)

Both opportunity and contact must belong to the authenticated user.
The association will be timestamped automatically.
 * @summary Create Opportunity Contact
 */
export const createOpportunityContactApiV1OpportunityContactsPost = (
    opportunityContactCreate: OpportunityContactCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OpportunityContact>(
      {url: `/api/v1/opportunity-contacts/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: opportunityContactCreate, signal
    },
      options);
    }
  


export const getCreateOpportunityContactApiV1OpportunityContactsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOpportunityContactApiV1OpportunityContactsPost>>, TError,{data: OpportunityContactCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createOpportunityContactApiV1OpportunityContactsPost>>, TError,{data: OpportunityContactCreate}, TContext> => {

const mutationKey = ['createOpportunityContactApiV1OpportunityContactsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOpportunityContactApiV1OpportunityContactsPost>>, {data: OpportunityContactCreate}> = (props) => {
          const {data} = props ?? {};

          return  createOpportunityContactApiV1OpportunityContactsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOpportunityContactApiV1OpportunityContactsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createOpportunityContactApiV1OpportunityContactsPost>>>
    export type CreateOpportunityContactApiV1OpportunityContactsPostMutationBody = OpportunityContactCreate
    export type CreateOpportunityContactApiV1OpportunityContactsPostMutationError = HTTPValidationError

    /**
 * @summary Create Opportunity Contact
 */
export const useCreateOpportunityContactApiV1OpportunityContactsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOpportunityContactApiV1OpportunityContactsPost>>, TError,{data: OpportunityContactCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOpportunityContactApiV1OpportunityContactsPost>>,
        TError,
        {data: OpportunityContactCreate},
        TContext
      > => {

      const mutationOptions = getCreateOpportunityContactApiV1OpportunityContactsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a specific opportunity-contact association by ID.

- **association_id**: The ID of the association to retrieve

Returns 404 if association doesn't exist or doesn't belong to the authenticated user.
 * @summary Get Opportunity Contact
 */
export const getOpportunityContactApiV1OpportunityContactsAssociationIdGet = (
    associationId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OpportunityContact>(
      {url: `/api/v1/opportunity-contacts/${associationId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetOpportunityContactApiV1OpportunityContactsAssociationIdGetQueryKey = (associationId?: number,) => {
    return [
    `/api/v1/opportunity-contacts/${associationId}`
    ] as const;
    }

    
export const getGetOpportunityContactApiV1OpportunityContactsAssociationIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>, TError = HTTPValidationError>(associationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOpportunityContactApiV1OpportunityContactsAssociationIdGetQueryKey(associationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>> = ({ signal }) => getOpportunityContactApiV1OpportunityContactsAssociationIdGet(associationId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(associationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOpportunityContactApiV1OpportunityContactsAssociationIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>>
export type GetOpportunityContactApiV1OpportunityContactsAssociationIdGetQueryError = HTTPValidationError


export function useGetOpportunityContactApiV1OpportunityContactsAssociationIdGet<TData = Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>, TError = HTTPValidationError>(
 associationId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>,
          TError,
          Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpportunityContactApiV1OpportunityContactsAssociationIdGet<TData = Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>, TError = HTTPValidationError>(
 associationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>,
          TError,
          Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpportunityContactApiV1OpportunityContactsAssociationIdGet<TData = Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>, TError = HTTPValidationError>(
 associationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Opportunity Contact
 */

export function useGetOpportunityContactApiV1OpportunityContactsAssociationIdGet<TData = Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>, TError = HTTPValidationError>(
 associationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityContactApiV1OpportunityContactsAssociationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOpportunityContactApiV1OpportunityContactsAssociationIdGetQueryOptions(associationId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing opportunity-contact association.

- **association_id**: The ID of the association to update
- All metadata fields are optional (is_primary_contact, contact_role, origin, notes)
- **Note**: Foreign keys (opportunity_id, contact_id) cannot be modified

Returns 404 if association doesn't exist or doesn't belong to the authenticated user.
 * @summary Update Opportunity Contact
 */
export const updateOpportunityContactApiV1OpportunityContactsAssociationIdPut = (
    associationId: number,
    opportunityContactUpdate: OpportunityContactUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<OpportunityContact>(
      {url: `/api/v1/opportunity-contacts/${associationId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: opportunityContactUpdate
    },
      options);
    }
  


export const getUpdateOpportunityContactApiV1OpportunityContactsAssociationIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOpportunityContactApiV1OpportunityContactsAssociationIdPut>>, TError,{associationId: number;data: OpportunityContactUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOpportunityContactApiV1OpportunityContactsAssociationIdPut>>, TError,{associationId: number;data: OpportunityContactUpdate}, TContext> => {

const mutationKey = ['updateOpportunityContactApiV1OpportunityContactsAssociationIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOpportunityContactApiV1OpportunityContactsAssociationIdPut>>, {associationId: number;data: OpportunityContactUpdate}> = (props) => {
          const {associationId,data} = props ?? {};

          return  updateOpportunityContactApiV1OpportunityContactsAssociationIdPut(associationId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOpportunityContactApiV1OpportunityContactsAssociationIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateOpportunityContactApiV1OpportunityContactsAssociationIdPut>>>
    export type UpdateOpportunityContactApiV1OpportunityContactsAssociationIdPutMutationBody = OpportunityContactUpdate
    export type UpdateOpportunityContactApiV1OpportunityContactsAssociationIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Opportunity Contact
 */
export const useUpdateOpportunityContactApiV1OpportunityContactsAssociationIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOpportunityContactApiV1OpportunityContactsAssociationIdPut>>, TError,{associationId: number;data: OpportunityContactUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOpportunityContactApiV1OpportunityContactsAssociationIdPut>>,
        TError,
        {associationId: number;data: OpportunityContactUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateOpportunityContactApiV1OpportunityContactsAssociationIdPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete an opportunity-contact association.

- **association_id**: The ID of the association to delete

Returns 404 if association doesn't exist or doesn't belong to the authenticated user.
 * @summary Delete Opportunity Contact
 */
export const deleteOpportunityContactApiV1OpportunityContactsAssociationIdDelete = (
    associationId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/opportunity-contacts/${associationId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteOpportunityContactApiV1OpportunityContactsAssociationIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOpportunityContactApiV1OpportunityContactsAssociationIdDelete>>, TError,{associationId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOpportunityContactApiV1OpportunityContactsAssociationIdDelete>>, TError,{associationId: number}, TContext> => {

const mutationKey = ['deleteOpportunityContactApiV1OpportunityContactsAssociationIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOpportunityContactApiV1OpportunityContactsAssociationIdDelete>>, {associationId: number}> = (props) => {
          const {associationId} = props ?? {};

          return  deleteOpportunityContactApiV1OpportunityContactsAssociationIdDelete(associationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOpportunityContactApiV1OpportunityContactsAssociationIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOpportunityContactApiV1OpportunityContactsAssociationIdDelete>>>
    
    export type DeleteOpportunityContactApiV1OpportunityContactsAssociationIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Opportunity Contact
 */
export const useDeleteOpportunityContactApiV1OpportunityContactsAssociationIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOpportunityContactApiV1OpportunityContactsAssociationIdDelete>>, TError,{associationId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOpportunityContactApiV1OpportunityContactsAssociationIdDelete>>,
        TError,
        {associationId: number},
        TContext
      > => {

      const mutationOptions = getDeleteOpportunityContactApiV1OpportunityContactsAssociationIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    