/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Contact,
  ContactCreate,
  ContactUpdate,
  GetContactsApiV1ContactsGetParams,
  HTTPValidationError
} from '.././model';

import { customInstance } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a list of contacts owned by the current user with pagination and optional filtering.

- **skip**: Number of records to skip (for pagination)
- **limit**: Maximum number of records to return (max 100)
- **company_id**: Optional filter by company ID
- **is_independent_recruiter**: Optional filter by independent recruiter status

Returns only contacts belonging to the authenticated user.
 * @summary Get Contacts
 */
export const getContactsApiV1ContactsGet = (
    params?: GetContactsApiV1ContactsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Contact[]>(
      {url: `/api/v1/contacts/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetContactsApiV1ContactsGetQueryKey = (params?: GetContactsApiV1ContactsGetParams,) => {
    return [
    `/api/v1/contacts/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetContactsApiV1ContactsGetQueryOptions = <TData = Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>, TError = HTTPValidationError>(params?: GetContactsApiV1ContactsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContactsApiV1ContactsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>> = ({ signal }) => getContactsApiV1ContactsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContactsApiV1ContactsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>>
export type GetContactsApiV1ContactsGetQueryError = HTTPValidationError


export function useGetContactsApiV1ContactsGet<TData = Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetContactsApiV1ContactsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>,
          TError,
          Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactsApiV1ContactsGet<TData = Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>, TError = HTTPValidationError>(
 params?: GetContactsApiV1ContactsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>,
          TError,
          Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactsApiV1ContactsGet<TData = Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>, TError = HTTPValidationError>(
 params?: GetContactsApiV1ContactsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Contacts
 */

export function useGetContactsApiV1ContactsGet<TData = Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>, TError = HTTPValidationError>(
 params?: GetContactsApiV1ContactsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsApiV1ContactsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContactsApiV1ContactsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new contact.

- **last_name**: Contact's last name (required)
- **first_name**: Contact's first name (required)
- **position**: Job title or position (optional)
- **email**: Email address (optional)
- **phone**: Phone number (optional)
- **linkedin**: LinkedIn profile URL (optional)
- **relationship_notes**: How you know this person - e.g., "Contacted on LinkedIn", "Former colleague" (optional)
- **is_independent_recruiter**: Whether this is an independent recruiter (default: false)
- **notes**: Additional notes (optional)
- **company_id**: Associated company ID (optional)

The contact will be automatically assigned to the authenticated user.
 * @summary Create Contact
 */
export const createContactApiV1ContactsPost = (
    contactCreate: ContactCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Contact>(
      {url: `/api/v1/contacts/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: contactCreate, signal
    },
      options);
    }
  


export const getCreateContactApiV1ContactsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContactApiV1ContactsPost>>, TError,{data: ContactCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createContactApiV1ContactsPost>>, TError,{data: ContactCreate}, TContext> => {

const mutationKey = ['createContactApiV1ContactsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createContactApiV1ContactsPost>>, {data: ContactCreate}> = (props) => {
          const {data} = props ?? {};

          return  createContactApiV1ContactsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateContactApiV1ContactsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createContactApiV1ContactsPost>>>
    export type CreateContactApiV1ContactsPostMutationBody = ContactCreate
    export type CreateContactApiV1ContactsPostMutationError = HTTPValidationError

    /**
 * @summary Create Contact
 */
export const useCreateContactApiV1ContactsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContactApiV1ContactsPost>>, TError,{data: ContactCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createContactApiV1ContactsPost>>,
        TError,
        {data: ContactCreate},
        TContext
      > => {

      const mutationOptions = getCreateContactApiV1ContactsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a specific contact by ID.

- **contact_id**: The ID of the contact to retrieve

Returns 404 if contact doesn't exist or doesn't belong to the authenticated user.
 * @summary Get Contact
 */
export const getContactApiV1ContactsContactIdGet = (
    contactId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Contact>(
      {url: `/api/v1/contacts/${contactId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetContactApiV1ContactsContactIdGetQueryKey = (contactId?: number,) => {
    return [
    `/api/v1/contacts/${contactId}`
    ] as const;
    }

    
export const getGetContactApiV1ContactsContactIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>, TError = HTTPValidationError>(contactId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContactApiV1ContactsContactIdGetQueryKey(contactId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>> = ({ signal }) => getContactApiV1ContactsContactIdGet(contactId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(contactId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContactApiV1ContactsContactIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>>
export type GetContactApiV1ContactsContactIdGetQueryError = HTTPValidationError


export function useGetContactApiV1ContactsContactIdGet<TData = Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>, TError = HTTPValidationError>(
 contactId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>,
          TError,
          Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactApiV1ContactsContactIdGet<TData = Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>, TError = HTTPValidationError>(
 contactId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>,
          TError,
          Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactApiV1ContactsContactIdGet<TData = Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>, TError = HTTPValidationError>(
 contactId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Contact
 */

export function useGetContactApiV1ContactsContactIdGet<TData = Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>, TError = HTTPValidationError>(
 contactId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactApiV1ContactsContactIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContactApiV1ContactsContactIdGetQueryOptions(contactId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing contact.

- **contact_id**: The ID of the contact to update
- All fields are optional - only provided fields will be updated

Returns 404 if contact doesn't exist or doesn't belong to the authenticated user.
 * @summary Update Contact
 */
export const updateContactApiV1ContactsContactIdPut = (
    contactId: number,
    contactUpdate: ContactUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Contact>(
      {url: `/api/v1/contacts/${contactId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: contactUpdate
    },
      options);
    }
  


export const getUpdateContactApiV1ContactsContactIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContactApiV1ContactsContactIdPut>>, TError,{contactId: number;data: ContactUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateContactApiV1ContactsContactIdPut>>, TError,{contactId: number;data: ContactUpdate}, TContext> => {

const mutationKey = ['updateContactApiV1ContactsContactIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateContactApiV1ContactsContactIdPut>>, {contactId: number;data: ContactUpdate}> = (props) => {
          const {contactId,data} = props ?? {};

          return  updateContactApiV1ContactsContactIdPut(contactId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateContactApiV1ContactsContactIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateContactApiV1ContactsContactIdPut>>>
    export type UpdateContactApiV1ContactsContactIdPutMutationBody = ContactUpdate
    export type UpdateContactApiV1ContactsContactIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Contact
 */
export const useUpdateContactApiV1ContactsContactIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContactApiV1ContactsContactIdPut>>, TError,{contactId: number;data: ContactUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateContactApiV1ContactsContactIdPut>>,
        TError,
        {contactId: number;data: ContactUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateContactApiV1ContactsContactIdPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a contact.

- **contact_id**: The ID of the contact to delete

Returns 404 if contact doesn't exist or doesn't belong to the authenticated user.
 * @summary Delete Contact
 */
export const deleteContactApiV1ContactsContactIdDelete = (
    contactId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/contacts/${contactId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteContactApiV1ContactsContactIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContactApiV1ContactsContactIdDelete>>, TError,{contactId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContactApiV1ContactsContactIdDelete>>, TError,{contactId: number}, TContext> => {

const mutationKey = ['deleteContactApiV1ContactsContactIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContactApiV1ContactsContactIdDelete>>, {contactId: number}> = (props) => {
          const {contactId} = props ?? {};

          return  deleteContactApiV1ContactsContactIdDelete(contactId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteContactApiV1ContactsContactIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContactApiV1ContactsContactIdDelete>>>
    
    export type DeleteContactApiV1ContactsContactIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Contact
 */
export const useDeleteContactApiV1ContactsContactIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContactApiV1ContactsContactIdDelete>>, TError,{contactId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteContactApiV1ContactsContactIdDelete>>,
        TError,
        {contactId: number},
        TContext
      > => {

      const mutationOptions = getDeleteContactApiV1ContactsContactIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    