/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetOpportunitiesApiV1OpportunitiesGetParams,
  HTTPValidationError,
  Opportunity,
  OpportunityCreate,
  OpportunityUpdate
} from '.././model';

import { customInstance } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a list of opportunities owned by the current user with pagination and optional filtering.

- **skip**: Number of records to skip (for pagination)
- **limit**: Maximum number of records to return (max 100)
- **company_id**: Optional filter by company ID
- **application_type**: Optional filter by type (job_posting, spontaneous, etc.)
- **contract_type**: Optional filter by contract (permanent, fixed_term, etc.)

Returns only opportunities belonging to the authenticated user.
 * @summary Get Opportunities
 */
export const getOpportunitiesApiV1OpportunitiesGet = (
    params?: GetOpportunitiesApiV1OpportunitiesGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Opportunity[]>(
      {url: `/api/v1/opportunities/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetOpportunitiesApiV1OpportunitiesGetQueryKey = (params?: GetOpportunitiesApiV1OpportunitiesGetParams,) => {
    return [
    `/api/v1/opportunities/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetOpportunitiesApiV1OpportunitiesGetQueryOptions = <TData = Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>, TError = HTTPValidationError>(params?: GetOpportunitiesApiV1OpportunitiesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOpportunitiesApiV1OpportunitiesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>> = ({ signal }) => getOpportunitiesApiV1OpportunitiesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOpportunitiesApiV1OpportunitiesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>>
export type GetOpportunitiesApiV1OpportunitiesGetQueryError = HTTPValidationError


export function useGetOpportunitiesApiV1OpportunitiesGet<TData = Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>, TError = HTTPValidationError>(
 params: undefined |  GetOpportunitiesApiV1OpportunitiesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>,
          TError,
          Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpportunitiesApiV1OpportunitiesGet<TData = Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>, TError = HTTPValidationError>(
 params?: GetOpportunitiesApiV1OpportunitiesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>,
          TError,
          Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpportunitiesApiV1OpportunitiesGet<TData = Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>, TError = HTTPValidationError>(
 params?: GetOpportunitiesApiV1OpportunitiesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Opportunities
 */

export function useGetOpportunitiesApiV1OpportunitiesGet<TData = Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>, TError = HTTPValidationError>(
 params?: GetOpportunitiesApiV1OpportunitiesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunitiesApiV1OpportunitiesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOpportunitiesApiV1OpportunitiesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new opportunity.

- **job_title**: Job title (required)
- **application_type**: Type of application (required)
- **position_type**: Role type (optional)
- **contract_type**: Type of contract (optional)
- **company_id**: Associated company ID (optional)
- ... and other optional details

The opportunity will be automatically assigned to the authenticated user.
 * @summary Create Opportunity
 */
export const createOpportunityApiV1OpportunitiesPost = (
    opportunityCreate: OpportunityCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Opportunity>(
      {url: `/api/v1/opportunities/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: opportunityCreate, signal
    },
      options);
    }
  


export const getCreateOpportunityApiV1OpportunitiesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOpportunityApiV1OpportunitiesPost>>, TError,{data: OpportunityCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createOpportunityApiV1OpportunitiesPost>>, TError,{data: OpportunityCreate}, TContext> => {

const mutationKey = ['createOpportunityApiV1OpportunitiesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOpportunityApiV1OpportunitiesPost>>, {data: OpportunityCreate}> = (props) => {
          const {data} = props ?? {};

          return  createOpportunityApiV1OpportunitiesPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOpportunityApiV1OpportunitiesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createOpportunityApiV1OpportunitiesPost>>>
    export type CreateOpportunityApiV1OpportunitiesPostMutationBody = OpportunityCreate
    export type CreateOpportunityApiV1OpportunitiesPostMutationError = HTTPValidationError

    /**
 * @summary Create Opportunity
 */
export const useCreateOpportunityApiV1OpportunitiesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOpportunityApiV1OpportunitiesPost>>, TError,{data: OpportunityCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOpportunityApiV1OpportunitiesPost>>,
        TError,
        {data: OpportunityCreate},
        TContext
      > => {

      const mutationOptions = getCreateOpportunityApiV1OpportunitiesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a specific opportunity by ID.

- **opportunity_id**: The ID of the opportunity to retrieve

Returns 404 if opportunity doesn't exist or doesn't belong to the authenticated user.
 * @summary Get Opportunity
 */
export const getOpportunityApiV1OpportunitiesOpportunityIdGet = (
    opportunityId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Opportunity>(
      {url: `/api/v1/opportunities/${opportunityId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetOpportunityApiV1OpportunitiesOpportunityIdGetQueryKey = (opportunityId?: number,) => {
    return [
    `/api/v1/opportunities/${opportunityId}`
    ] as const;
    }

    
export const getGetOpportunityApiV1OpportunitiesOpportunityIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>, TError = HTTPValidationError>(opportunityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOpportunityApiV1OpportunitiesOpportunityIdGetQueryKey(opportunityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>> = ({ signal }) => getOpportunityApiV1OpportunitiesOpportunityIdGet(opportunityId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(opportunityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOpportunityApiV1OpportunitiesOpportunityIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>>
export type GetOpportunityApiV1OpportunitiesOpportunityIdGetQueryError = HTTPValidationError


export function useGetOpportunityApiV1OpportunitiesOpportunityIdGet<TData = Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>, TError = HTTPValidationError>(
 opportunityId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>,
          TError,
          Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpportunityApiV1OpportunitiesOpportunityIdGet<TData = Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>, TError = HTTPValidationError>(
 opportunityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>,
          TError,
          Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpportunityApiV1OpportunitiesOpportunityIdGet<TData = Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>, TError = HTTPValidationError>(
 opportunityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Opportunity
 */

export function useGetOpportunityApiV1OpportunitiesOpportunityIdGet<TData = Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>, TError = HTTPValidationError>(
 opportunityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityApiV1OpportunitiesOpportunityIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOpportunityApiV1OpportunitiesOpportunityIdGetQueryOptions(opportunityId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing opportunity.

- **opportunity_id**: The ID of the opportunity to update
- All fields are optional - only provided fields will be updated

Returns 404 if opportunity doesn't exist or doesn't belong to the authenticated user.
 * @summary Update Opportunity
 */
export const updateOpportunityApiV1OpportunitiesOpportunityIdPut = (
    opportunityId: number,
    opportunityUpdate: OpportunityUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Opportunity>(
      {url: `/api/v1/opportunities/${opportunityId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: opportunityUpdate
    },
      options);
    }
  


export const getUpdateOpportunityApiV1OpportunitiesOpportunityIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOpportunityApiV1OpportunitiesOpportunityIdPut>>, TError,{opportunityId: number;data: OpportunityUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOpportunityApiV1OpportunitiesOpportunityIdPut>>, TError,{opportunityId: number;data: OpportunityUpdate}, TContext> => {

const mutationKey = ['updateOpportunityApiV1OpportunitiesOpportunityIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOpportunityApiV1OpportunitiesOpportunityIdPut>>, {opportunityId: number;data: OpportunityUpdate}> = (props) => {
          const {opportunityId,data} = props ?? {};

          return  updateOpportunityApiV1OpportunitiesOpportunityIdPut(opportunityId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOpportunityApiV1OpportunitiesOpportunityIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateOpportunityApiV1OpportunitiesOpportunityIdPut>>>
    export type UpdateOpportunityApiV1OpportunitiesOpportunityIdPutMutationBody = OpportunityUpdate
    export type UpdateOpportunityApiV1OpportunitiesOpportunityIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Opportunity
 */
export const useUpdateOpportunityApiV1OpportunitiesOpportunityIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOpportunityApiV1OpportunitiesOpportunityIdPut>>, TError,{opportunityId: number;data: OpportunityUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOpportunityApiV1OpportunitiesOpportunityIdPut>>,
        TError,
        {opportunityId: number;data: OpportunityUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateOpportunityApiV1OpportunitiesOpportunityIdPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete an opportunity.

- **opportunity_id**: The ID of the opportunity to delete

Returns 404 if opportunity doesn't exist or doesn't belong to the authenticated user.
 * @summary Delete Opportunity
 */
export const deleteOpportunityApiV1OpportunitiesOpportunityIdDelete = (
    opportunityId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/opportunities/${opportunityId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteOpportunityApiV1OpportunitiesOpportunityIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOpportunityApiV1OpportunitiesOpportunityIdDelete>>, TError,{opportunityId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOpportunityApiV1OpportunitiesOpportunityIdDelete>>, TError,{opportunityId: number}, TContext> => {

const mutationKey = ['deleteOpportunityApiV1OpportunitiesOpportunityIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOpportunityApiV1OpportunitiesOpportunityIdDelete>>, {opportunityId: number}> = (props) => {
          const {opportunityId} = props ?? {};

          return  deleteOpportunityApiV1OpportunitiesOpportunityIdDelete(opportunityId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOpportunityApiV1OpportunitiesOpportunityIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOpportunityApiV1OpportunitiesOpportunityIdDelete>>>
    
    export type DeleteOpportunityApiV1OpportunitiesOpportunityIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Opportunity
 */
export const useDeleteOpportunityApiV1OpportunitiesOpportunityIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOpportunityApiV1OpportunitiesOpportunityIdDelete>>, TError,{opportunityId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOpportunityApiV1OpportunitiesOpportunityIdDelete>>,
        TError,
        {opportunityId: number},
        TContext
      > => {

      const mutationOptions = getDeleteOpportunityApiV1OpportunitiesOpportunityIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    