/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DocumentAssociation,
  DocumentAssociationCreate,
  GetDocumentAssociationsApiV1DocumentAssociationsGetParams,
  HTTPValidationError
} from '.././model';

import { customInstance } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a list of document associations owned by the current user with pagination and filtering.

- **skip**: Number of records to skip (for pagination)
- **limit**: Maximum number of records to return (max 100)
- **document_id**: Optional filter by document ID
- **entity_type**: Optional filter by entity type
- **entity_id**: Optional filter by entity ID (requires entity_type to be specified)

Returns only associations where the document belongs to the authenticated user.
 * @summary Get Document Associations
 */
export const getDocumentAssociationsApiV1DocumentAssociationsGet = (
    params?: GetDocumentAssociationsApiV1DocumentAssociationsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentAssociation[]>(
      {url: `/api/v1/document-associations/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetDocumentAssociationsApiV1DocumentAssociationsGetQueryKey = (params?: GetDocumentAssociationsApiV1DocumentAssociationsGetParams,) => {
    return [
    `/api/v1/document-associations/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetDocumentAssociationsApiV1DocumentAssociationsGetQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>, TError = HTTPValidationError>(params?: GetDocumentAssociationsApiV1DocumentAssociationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentAssociationsApiV1DocumentAssociationsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>> = ({ signal }) => getDocumentAssociationsApiV1DocumentAssociationsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentAssociationsApiV1DocumentAssociationsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>>
export type GetDocumentAssociationsApiV1DocumentAssociationsGetQueryError = HTTPValidationError


export function useGetDocumentAssociationsApiV1DocumentAssociationsGet<TData = Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetDocumentAssociationsApiV1DocumentAssociationsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>,
          TError,
          Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentAssociationsApiV1DocumentAssociationsGet<TData = Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>, TError = HTTPValidationError>(
 params?: GetDocumentAssociationsApiV1DocumentAssociationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>,
          TError,
          Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentAssociationsApiV1DocumentAssociationsGet<TData = Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>, TError = HTTPValidationError>(
 params?: GetDocumentAssociationsApiV1DocumentAssociationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Document Associations
 */

export function useGetDocumentAssociationsApiV1DocumentAssociationsGet<TData = Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>, TError = HTTPValidationError>(
 params?: GetDocumentAssociationsApiV1DocumentAssociationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentAssociationsApiV1DocumentAssociationsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentAssociationsApiV1DocumentAssociationsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new link between a document and any entity.

- **document_id**: ID of the document (required)
- **entity_type**: Type of entity (application, opportunity, company, contact)
- **entity_id**: ID of the entity (required)

Both document and entity must belong to the authenticated user.
The association will be timestamped automatically.
 * @summary Create Document Association
 */
export const createDocumentAssociationApiV1DocumentAssociationsPost = (
    documentAssociationCreate: DocumentAssociationCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentAssociation>(
      {url: `/api/v1/document-associations/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: documentAssociationCreate, signal
    },
      options);
    }
  


export const getCreateDocumentAssociationApiV1DocumentAssociationsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDocumentAssociationApiV1DocumentAssociationsPost>>, TError,{data: DocumentAssociationCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createDocumentAssociationApiV1DocumentAssociationsPost>>, TError,{data: DocumentAssociationCreate}, TContext> => {

const mutationKey = ['createDocumentAssociationApiV1DocumentAssociationsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDocumentAssociationApiV1DocumentAssociationsPost>>, {data: DocumentAssociationCreate}> = (props) => {
          const {data} = props ?? {};

          return  createDocumentAssociationApiV1DocumentAssociationsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDocumentAssociationApiV1DocumentAssociationsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createDocumentAssociationApiV1DocumentAssociationsPost>>>
    export type CreateDocumentAssociationApiV1DocumentAssociationsPostMutationBody = DocumentAssociationCreate
    export type CreateDocumentAssociationApiV1DocumentAssociationsPostMutationError = HTTPValidationError

    /**
 * @summary Create Document Association
 */
export const useCreateDocumentAssociationApiV1DocumentAssociationsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDocumentAssociationApiV1DocumentAssociationsPost>>, TError,{data: DocumentAssociationCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDocumentAssociationApiV1DocumentAssociationsPost>>,
        TError,
        {data: DocumentAssociationCreate},
        TContext
      > => {

      const mutationOptions = getCreateDocumentAssociationApiV1DocumentAssociationsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a specific document association by ID.

- **association_id**: The ID of the association to retrieve

Returns 404 if association doesn't exist or doesn't belong to the authenticated user.
 * @summary Get Document Association
 */
export const getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet = (
    associationId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentAssociation>(
      {url: `/api/v1/document-associations/${associationId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDocumentAssociationApiV1DocumentAssociationsAssociationIdGetQueryKey = (associationId?: number,) => {
    return [
    `/api/v1/document-associations/${associationId}`
    ] as const;
    }

    
export const getGetDocumentAssociationApiV1DocumentAssociationsAssociationIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>, TError = HTTPValidationError>(associationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentAssociationApiV1DocumentAssociationsAssociationIdGetQueryKey(associationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>> = ({ signal }) => getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet(associationId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(associationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentAssociationApiV1DocumentAssociationsAssociationIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>>
export type GetDocumentAssociationApiV1DocumentAssociationsAssociationIdGetQueryError = HTTPValidationError


export function useGetDocumentAssociationApiV1DocumentAssociationsAssociationIdGet<TData = Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>, TError = HTTPValidationError>(
 associationId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>,
          TError,
          Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentAssociationApiV1DocumentAssociationsAssociationIdGet<TData = Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>, TError = HTTPValidationError>(
 associationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>,
          TError,
          Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentAssociationApiV1DocumentAssociationsAssociationIdGet<TData = Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>, TError = HTTPValidationError>(
 associationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Document Association
 */

export function useGetDocumentAssociationApiV1DocumentAssociationsAssociationIdGet<TData = Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>, TError = HTTPValidationError>(
 associationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentAssociationApiV1DocumentAssociationsAssociationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentAssociationApiV1DocumentAssociationsAssociationIdGetQueryOptions(associationId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Delete a document association.

- **association_id**: The ID of the association to delete

Returns 404 if association doesn't exist or doesn't belong to the authenticated user.
 * @summary Delete Document Association
 */
export const deleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDelete = (
    associationId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/document-associations/${associationId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDelete>>, TError,{associationId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDelete>>, TError,{associationId: number}, TContext> => {

const mutationKey = ['deleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDelete>>, {associationId: number}> = (props) => {
          const {associationId} = props ?? {};

          return  deleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDelete(associationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDelete>>>
    
    export type DeleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Document Association
 */
export const useDeleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDelete>>, TError,{associationId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDelete>>,
        TError,
        {associationId: number},
        TContext
      > => {

      const mutationOptions = getDeleteDocumentAssociationApiV1DocumentAssociationsAssociationIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    