/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Application,
  ApplicationCreate,
  ApplicationUpdate,
  ApplicationWithOpportunityCreate,
  GetApplicationsApiV1ApplicationsGetParams,
  HTTPValidationError
} from '.././model';

import { customInstance } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a list of applications owned by the current user with pagination and optional filtering.

- **skip**: Number of records to skip (for pagination)
- **limit**: Maximum number of records to return (max 100)
- **opportunity_id**: Optional filter by opportunity ID
- **status**: Optional filter by status (pending, rejected, accepted, etc.)
- **is_archived**: Optional filter by archive status

Returns only applications belonging to the authenticated user (owner_id direct).
 * @summary Get Applications
 */
export const getApplicationsApiV1ApplicationsGet = (
    params?: GetApplicationsApiV1ApplicationsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Application[]>(
      {url: `/api/v1/applications/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApplicationsApiV1ApplicationsGetQueryKey = (params?: GetApplicationsApiV1ApplicationsGetParams,) => {
    return [
    `/api/v1/applications/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApplicationsApiV1ApplicationsGetQueryOptions = <TData = Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>, TError = HTTPValidationError>(params?: GetApplicationsApiV1ApplicationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApplicationsApiV1ApplicationsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>> = ({ signal }) => getApplicationsApiV1ApplicationsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApplicationsApiV1ApplicationsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>>
export type GetApplicationsApiV1ApplicationsGetQueryError = HTTPValidationError


export function useGetApplicationsApiV1ApplicationsGet<TData = Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetApplicationsApiV1ApplicationsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>,
          TError,
          Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplicationsApiV1ApplicationsGet<TData = Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>, TError = HTTPValidationError>(
 params?: GetApplicationsApiV1ApplicationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>,
          TError,
          Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplicationsApiV1ApplicationsGet<TData = Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>, TError = HTTPValidationError>(
 params?: GetApplicationsApiV1ApplicationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Applications
 */

export function useGetApplicationsApiV1ApplicationsGet<TData = Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>, TError = HTTPValidationError>(
 params?: GetApplicationsApiV1ApplicationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationsApiV1ApplicationsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApplicationsApiV1ApplicationsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new application.

**Required Fields:**
- **opportunity_id**: ID of the opportunity (must exist and belong to user)
- **application_date**: Date of application (ISO format)

**Optional Fields:**
- **resume_used_id**: ID of resume document (auto-creates DocumentAssociation)
- **cover_letter_id**: ID of cover letter document (auto-creates DocumentAssociation)
- **status**: Application status (default: "pending")
- **notes**: Additional notes

**Automatic Associations:**
When resume_used_id or cover_letter_id are provided, the system automatically
creates DocumentAssociation linking the document to this application.

**Returns:**
- **201**: Application created successfully

**Raises:**
- **400**: Opportunity doesn't exist or belong to user
- **404**: Document (resume/cover_letter) doesn't exist or belong to user
- **401**: Unauthorized
- **422**: Validation error
 * @summary Create Application
 */
export const createApplicationApiV1ApplicationsPost = (
    applicationCreate: ApplicationCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Application>(
      {url: `/api/v1/applications/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: applicationCreate, signal
    },
      options);
    }
  


export const getCreateApplicationApiV1ApplicationsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApplicationApiV1ApplicationsPost>>, TError,{data: ApplicationCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createApplicationApiV1ApplicationsPost>>, TError,{data: ApplicationCreate}, TContext> => {

const mutationKey = ['createApplicationApiV1ApplicationsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createApplicationApiV1ApplicationsPost>>, {data: ApplicationCreate}> = (props) => {
          const {data} = props ?? {};

          return  createApplicationApiV1ApplicationsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateApplicationApiV1ApplicationsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createApplicationApiV1ApplicationsPost>>>
    export type CreateApplicationApiV1ApplicationsPostMutationBody = ApplicationCreate
    export type CreateApplicationApiV1ApplicationsPostMutationError = HTTPValidationError

    /**
 * @summary Create Application
 */
export const useCreateApplicationApiV1ApplicationsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApplicationApiV1ApplicationsPost>>, TError,{data: ApplicationCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createApplicationApiV1ApplicationsPost>>,
        TError,
        {data: ApplicationCreate},
        TContext
      > => {

      const mutationOptions = getCreateApplicationApiV1ApplicationsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a specific application by ID.

- **application_id**: The ID of the application to retrieve

Returns 404 if application doesn't exist or doesn't belong to the authenticated user.
 * @summary Get Application
 */
export const getApplicationApiV1ApplicationsApplicationIdGet = (
    applicationId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Application>(
      {url: `/api/v1/applications/${applicationId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApplicationApiV1ApplicationsApplicationIdGetQueryKey = (applicationId?: number,) => {
    return [
    `/api/v1/applications/${applicationId}`
    ] as const;
    }

    
export const getGetApplicationApiV1ApplicationsApplicationIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>, TError = HTTPValidationError>(applicationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApplicationApiV1ApplicationsApplicationIdGetQueryKey(applicationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>> = ({ signal }) => getApplicationApiV1ApplicationsApplicationIdGet(applicationId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(applicationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApplicationApiV1ApplicationsApplicationIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>>
export type GetApplicationApiV1ApplicationsApplicationIdGetQueryError = HTTPValidationError


export function useGetApplicationApiV1ApplicationsApplicationIdGet<TData = Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>, TError = HTTPValidationError>(
 applicationId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>,
          TError,
          Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplicationApiV1ApplicationsApplicationIdGet<TData = Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>, TError = HTTPValidationError>(
 applicationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>,
          TError,
          Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplicationApiV1ApplicationsApplicationIdGet<TData = Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>, TError = HTTPValidationError>(
 applicationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Application
 */

export function useGetApplicationApiV1ApplicationsApplicationIdGet<TData = Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>, TError = HTTPValidationError>(
 applicationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationApiV1ApplicationsApplicationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApplicationApiV1ApplicationsApplicationIdGetQueryOptions(applicationId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing application.

**Updatable Fields:**
- **opportunity_id**: Change linked opportunity (must exist and belong to user)
- **application_date**: Update application date
- **resume_used_id**: Change resume (auto-updates DocumentAssociation)
- **cover_letter_id**: Change cover letter (auto-updates DocumentAssociation)
- **status**: Update status
- **notes**: Update notes

**Automatic Association Management:**
- Setting resume_used_id/cover_letter_id → creates DocumentAssociation
- Changing resume_used_id/cover_letter_id → updates DocumentAssociation
- Setting to null → removes DocumentAssociation

**Returns:**
- **200**: Application updated successfully

**Raises:**
- **400**: Opportunity doesn't exist or belong to user
- **404**: Application or document not found or doesn't belong to user
- **401**: Unauthorized
- **422**: Validation error
 * @summary Update Application
 */
export const updateApplicationApiV1ApplicationsApplicationIdPut = (
    applicationId: number,
    applicationUpdate: ApplicationUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Application>(
      {url: `/api/v1/applications/${applicationId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: applicationUpdate
    },
      options);
    }
  


export const getUpdateApplicationApiV1ApplicationsApplicationIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateApplicationApiV1ApplicationsApplicationIdPut>>, TError,{applicationId: number;data: ApplicationUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateApplicationApiV1ApplicationsApplicationIdPut>>, TError,{applicationId: number;data: ApplicationUpdate}, TContext> => {

const mutationKey = ['updateApplicationApiV1ApplicationsApplicationIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateApplicationApiV1ApplicationsApplicationIdPut>>, {applicationId: number;data: ApplicationUpdate}> = (props) => {
          const {applicationId,data} = props ?? {};

          return  updateApplicationApiV1ApplicationsApplicationIdPut(applicationId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateApplicationApiV1ApplicationsApplicationIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateApplicationApiV1ApplicationsApplicationIdPut>>>
    export type UpdateApplicationApiV1ApplicationsApplicationIdPutMutationBody = ApplicationUpdate
    export type UpdateApplicationApiV1ApplicationsApplicationIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Application
 */
export const useUpdateApplicationApiV1ApplicationsApplicationIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateApplicationApiV1ApplicationsApplicationIdPut>>, TError,{applicationId: number;data: ApplicationUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateApplicationApiV1ApplicationsApplicationIdPut>>,
        TError,
        {applicationId: number;data: ApplicationUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateApplicationApiV1ApplicationsApplicationIdPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete an application.

- **application_id**: The ID of the application to delete

Returns 404 if application doesn't exist or doesn't belong to the authenticated user.
 * @summary Delete Application
 */
export const deleteApplicationApiV1ApplicationsApplicationIdDelete = (
    applicationId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/applications/${applicationId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApplicationApiV1ApplicationsApplicationIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApplicationApiV1ApplicationsApplicationIdDelete>>, TError,{applicationId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApplicationApiV1ApplicationsApplicationIdDelete>>, TError,{applicationId: number}, TContext> => {

const mutationKey = ['deleteApplicationApiV1ApplicationsApplicationIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApplicationApiV1ApplicationsApplicationIdDelete>>, {applicationId: number}> = (props) => {
          const {applicationId} = props ?? {};

          return  deleteApplicationApiV1ApplicationsApplicationIdDelete(applicationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApplicationApiV1ApplicationsApplicationIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApplicationApiV1ApplicationsApplicationIdDelete>>>
    
    export type DeleteApplicationApiV1ApplicationsApplicationIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Application
 */
export const useDeleteApplicationApiV1ApplicationsApplicationIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApplicationApiV1ApplicationsApplicationIdDelete>>, TError,{applicationId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApplicationApiV1ApplicationsApplicationIdDelete>>,
        TError,
        {applicationId: number},
        TContext
      > => {

      const mutationOptions = getDeleteApplicationApiV1ApplicationsApplicationIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Create an application and its linked opportunity in a single request.

**Composite Endpoint Benefits:**
- Atomicity: Both opportunity and application created in single transaction
- Convenience: No need for separate API calls
- Consistency: Guaranteed link between opportunity and application

**Request Structure:**
- **opportunity**: OpportunityCreate object (without opportunity_id)
- **application_date**: Date of application
- **resume_used_id**: Optional resume document (auto-creates DocumentAssociation)
- **cover_letter_id**: Optional cover letter document (auto-creates DocumentAssociation)
- **status**: Optional status (default: "pending")
- **notes**: Optional notes

**Automatic Associations:**
When resume_used_id or cover_letter_id are provided, the system automatically
creates DocumentAssociation linking the documents to the new application.

**Returns:**
- **201**: Application (with embedded opportunity_id) created successfully

**Raises:**
- **400**: Company doesn't exist or belong to user
- **404**: Document (resume/cover_letter) doesn't exist or belong to user
- **401**: Unauthorized
- **422**: Validation error
 * @summary Create Application With Opportunity
 */
export const createApplicationWithOpportunityApiV1ApplicationsWithOpportunityPost = (
    applicationWithOpportunityCreate: ApplicationWithOpportunityCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Application>(
      {url: `/api/v1/applications/with-opportunity`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: applicationWithOpportunityCreate, signal
    },
      options);
    }
  


export const getCreateApplicationWithOpportunityApiV1ApplicationsWithOpportunityPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApplicationWithOpportunityApiV1ApplicationsWithOpportunityPost>>, TError,{data: ApplicationWithOpportunityCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createApplicationWithOpportunityApiV1ApplicationsWithOpportunityPost>>, TError,{data: ApplicationWithOpportunityCreate}, TContext> => {

const mutationKey = ['createApplicationWithOpportunityApiV1ApplicationsWithOpportunityPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createApplicationWithOpportunityApiV1ApplicationsWithOpportunityPost>>, {data: ApplicationWithOpportunityCreate}> = (props) => {
          const {data} = props ?? {};

          return  createApplicationWithOpportunityApiV1ApplicationsWithOpportunityPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateApplicationWithOpportunityApiV1ApplicationsWithOpportunityPostMutationResult = NonNullable<Awaited<ReturnType<typeof createApplicationWithOpportunityApiV1ApplicationsWithOpportunityPost>>>
    export type CreateApplicationWithOpportunityApiV1ApplicationsWithOpportunityPostMutationBody = ApplicationWithOpportunityCreate
    export type CreateApplicationWithOpportunityApiV1ApplicationsWithOpportunityPostMutationError = HTTPValidationError

    /**
 * @summary Create Application With Opportunity
 */
export const useCreateApplicationWithOpportunityApiV1ApplicationsWithOpportunityPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApplicationWithOpportunityApiV1ApplicationsWithOpportunityPost>>, TError,{data: ApplicationWithOpportunityCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createApplicationWithOpportunityApiV1ApplicationsWithOpportunityPost>>,
        TError,
        {data: ApplicationWithOpportunityCreate},
        TContext
      > => {

      const mutationOptions = getCreateApplicationWithOpportunityApiV1ApplicationsWithOpportunityPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    