/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ActionUpdateType } from './actionUpdateType';
import type { ActionUpdateCompletedDate } from './actionUpdateCompletedDate';
import type { ActionUpdateNotes } from './actionUpdateNotes';
import type { ActionUpdateScheduledEventId } from './actionUpdateScheduledEventId';
import type { ActionUpdateApplicationId } from './actionUpdateApplicationId';

/**
 * Schema for updating an action (PUT/PATCH).
All fields are optional to support partial updates.
 */
export interface ActionUpdate {
  type?: ActionUpdateType;
  completed_date?: ActionUpdateCompletedDate;
  notes?: ActionUpdateNotes;
  scheduled_event_id?: ActionUpdateScheduledEventId;
  application_id?: ActionUpdateApplicationId;
}
