/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ActionCreateCompletedDate } from './actionCreateCompletedDate';
import type { ActionCreateNotes } from './actionCreateNotes';
import type { ActionCreateScheduledEventId } from './actionCreateScheduledEventId';

/**
 * Schema for creating a new action (POST).
 */
export interface ActionCreate {
  /**
   * Type of action (follow_up, note, etc.)
   * @minLength 1
   * @maxLength 50
   */
  type: string;
  /** Date when action was completed (NULL = ongoing) */
  completed_date?: ActionCreateCompletedDate;
  /** Details or notes about the action */
  notes?: ActionCreateNotes;
  /** ID of associated scheduled event */
  scheduled_event_id?: ActionCreateScheduledEventId;
  /**
   * ID of the related application
   */
  application_id: number;
}
