/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ActionCompletedDate } from './actionCompletedDate';
import type { ActionNotes } from './actionNotes';
import type { ActionScheduledEventId } from './actionScheduledEventId';
import type { ActionUpdatedAt } from './actionUpdatedAt';

/**
 * Schema for reading an action (GET).
Includes all fields including generated ones (id, timestamps).
 */
export interface Action {
  /**
   * Type of action (follow_up, note, etc.)
   * @minLength 1
   * @maxLength 50
   */
  type: string;
  /** Date when action was completed (NULL = ongoing) */
  completed_date?: ActionCompletedDate;
  /** Details or notes about the action */
  notes?: ActionNotes;
  /** ID of associated scheduled event */
  scheduled_event_id?: ActionScheduledEventId;
  /** Unique identifier */
  id: number;
  /** Owner user ID */
  owner_id: number;
  /** ID of the related application */
  application_id: number;
  /** Creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at?: ActionUpdatedAt;
}
