/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * ID of associated scheduled event
 */
export type ActionCreateScheduledEventId = number | null;
