/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { OpportunityCreate } from './opportunityCreate';
import type { ApplicationCreateWithoutOpportunityId } from './applicationCreateWithoutOpportunityId';

/**
 * Composite schema for creating Application with its Opportunity in one call.

Used when the opportunity doesn't exist yet (new job application).
Frontend sends both opportunity details and application details,
backend creates them in a single transaction.

Example:
{
    "opportunity": {
        "job_title": "Senior Python Developer",
        "application_type": "job_posting",
        "company_id": 42,
        ...
    },
    "application": {
        "application_date": "2024-12-02",
        "status": "pending",
        "resume_used_id": 5
    }
}
 */
export interface ApplicationWithOpportunityCreate {
  /** Opportunity details to create */
  opportunity: OpportunityCreate;
  /** Application details to create */
  application: ApplicationCreateWithoutOpportunityId;
}
