/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ApplicationStatus } from './applicationStatus';
import type { ApplicationCreateSalaryExpectation } from './applicationCreateSalaryExpectation';
import type { ApplicationCreateResumeUsedId } from './applicationCreateResumeUsedId';
import type { ApplicationCreateCoverLetterId } from './applicationCreateCoverLetterId';

/**
 * Schema for creating a new application (POST).
 */
export interface ApplicationCreate {
  /** Date when the application was sent */
  application_date: string;
  /** Current status of the application */
  status?: ApplicationStatus;
  /** Expected gross annual salary */
  salary_expectation?: ApplicationCreateSalaryExpectation;
  /** Whether the application is archived */
  is_archived?: boolean;
  /** ID of the resume (Document) used */
  resume_used_id?: ApplicationCreateResumeUsedId;
  /** ID of the cover letter (Document) used */
  cover_letter_id?: ApplicationCreateCoverLetterId;
  /**
   * ID of the related opportunity
   */
  opportunity_id: number;
}
