/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ApplicationStatus } from './applicationStatus';
import type { ApplicationCreateWithoutOpportunityIdSalaryExpectation } from './applicationCreateWithoutOpportunityIdSalaryExpectation';
import type { ApplicationCreateWithoutOpportunityIdResumeUsedId } from './applicationCreateWithoutOpportunityIdResumeUsedId';
import type { ApplicationCreateWithoutOpportunityIdCoverLetterId } from './applicationCreateWithoutOpportunityIdCoverLetterId';

/**
 * Schema for creating an application without opportunity_id.
Used in composite endpoint where opportunity is created at the same time.
 */
export interface ApplicationCreateWithoutOpportunityId {
  /** Date when the application was sent */
  application_date: string;
  /** Current status of the application */
  status?: ApplicationStatus;
  /** Expected gross annual salary */
  salary_expectation?: ApplicationCreateWithoutOpportunityIdSalaryExpectation;
  /** Whether the application is archived */
  is_archived?: boolean;
  /** ID of the resume (Document) used */
  resume_used_id?: ApplicationCreateWithoutOpportunityIdResumeUsedId;
  /** ID of the cover letter (Document) used */
  cover_letter_id?: ApplicationCreateWithoutOpportunityIdCoverLetterId;
}
