/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ApplicationStatus } from './applicationStatus';
import type { ApplicationSalaryExpectation } from './applicationSalaryExpectation';
import type { ApplicationResumeUsedId } from './applicationResumeUsedId';
import type { ApplicationCoverLetterId } from './applicationCoverLetterId';
import type { ApplicationUpdatedAt } from './applicationUpdatedAt';
import type { Opportunity } from './opportunity';
import type { ApplicationResumeUsed } from './applicationResumeUsed';
import type { ApplicationCoverLetter } from './applicationCoverLetter';

/**
 * Schema for reading an application (GET).
Includes all fields including generated ones (id, timestamps).
 */
export interface Application {
  /** Date when the application was sent */
  application_date: string;
  /** Current status of the application */
  status?: ApplicationStatus;
  /** Expected gross annual salary */
  salary_expectation?: ApplicationSalaryExpectation;
  /** Whether the application is archived */
  is_archived?: boolean;
  /** ID of the resume (Document) used */
  resume_used_id?: ApplicationResumeUsedId;
  /** ID of the cover letter (Document) used */
  cover_letter_id?: ApplicationCoverLetterId;
  /** Unique identifier */
  id: number;
  /** Owner user ID */
  owner_id: number;
  /** ID of the related opportunity */
  opportunity_id: number;
  /** Creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at?: ApplicationUpdatedAt;
  opportunity: Opportunity;
  resume_used?: ApplicationResumeUsed;
  cover_letter?: ApplicationCoverLetter;
}
