/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ApplicationUpdateApplicationDate } from './applicationUpdateApplicationDate';
import type { ApplicationUpdateStatus } from './applicationUpdateStatus';
import type { ApplicationUpdateSalaryExpectation } from './applicationUpdateSalaryExpectation';
import type { ApplicationUpdateIsArchived } from './applicationUpdateIsArchived';
import type { ApplicationUpdateResumeUsedId } from './applicationUpdateResumeUsedId';
import type { ApplicationUpdateCoverLetterId } from './applicationUpdateCoverLetterId';
import type { ApplicationUpdateOpportunityId } from './applicationUpdateOpportunityId';

/**
 * Schema for updating an application (PUT/PATCH).
All fields are optional to support partial updates.
 */
export interface ApplicationUpdate {
  application_date?: ApplicationUpdateApplicationDate;
  status?: ApplicationUpdateStatus;
  salary_expectation?: ApplicationUpdateSalaryExpectation;
  is_archived?: ApplicationUpdateIsArchived;
  resume_used_id?: ApplicationUpdateResumeUsedId;
  cover_letter_id?: ApplicationUpdateCoverLetterId;
  opportunity_id?: ApplicationUpdateOpportunityId;
}
