/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

export interface BodyUploadDocumentApiV1DocumentsUploadPost {
  /** File to upload */
  file: Blob;
  /**
   * Document name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * Document type
   * @minLength 1
   * @maxLength 50
   */
  type: string;
  /**
   * Optional description
   * @maxLength 5000
   */
  description?: string;
}
