/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Method of communication for the event.
 */
export type CommunicationMethod = typeof CommunicationMethod[keyof typeof CommunicationMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommunicationMethod = {
  video: 'video',
  phone: 'phone',
  in_person: 'in_person',
  email: 'email',
  other: 'other',
} as const;
