/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { CompanyUpdateName } from './companyUpdateName';
import type { CompanyUpdateSiret } from './companyUpdateSiret';
import type { CompanyUpdateWebsite } from './companyUpdateWebsite';
import type { CompanyUpdateHeadquarters } from './companyUpdateHeadquarters';
import type { CompanyUpdateIsIntermediary } from './companyUpdateIsIntermediary';
import type { CompanyUpdateCompanyType } from './companyUpdateCompanyType';
import type { CompanyUpdateIndustry } from './companyUpdateIndustry';
import type { CompanyUpdateNotes } from './companyUpdateNotes';

/**
 * Schema for updating a company (PUT/PATCH).

All fields are optional to support partial updates.
 */
export interface CompanyUpdate {
  name?: CompanyUpdateName;
  siret?: CompanyUpdateSiret;
  website?: CompanyUpdateWebsite;
  headquarters?: CompanyUpdateHeadquarters;
  is_intermediary?: CompanyUpdateIsIntermediary;
  company_type?: CompanyUpdateCompanyType;
  industry?: CompanyUpdateIndustry;
  notes?: CompanyUpdateNotes;
}
