/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { CompanySiret } from './companySiret';
import type { CompanyWebsite } from './companyWebsite';
import type { CompanyHeadquarters } from './companyHeadquarters';
import type { CompanyCompanyType } from './companyCompanyType';
import type { CompanyIndustry } from './companyIndustry';
import type { CompanyNotes } from './companyNotes';
import type { CompanyUpdatedAt } from './companyUpdatedAt';

/**
 * Schema for reading a company (GET).

Includes all fields including generated ones (id, timestamps).
 */
export interface Company {
  /**
   * Company name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** French business ID (SIRET) */
  siret?: CompanySiret;
  /** Company website URL */
  website?: CompanyWebsite;
  /** Company headquarters address */
  headquarters?: CompanyHeadquarters;
  /** Whether this company is an intermediary (ESN, agency) */
  is_intermediary?: boolean;
  /** Type: ESN, startup, enterprise, SME, etc. */
  company_type?: CompanyCompanyType;
  /** Industry: Healthcare, automotive, etc. */
  industry?: CompanyIndustry;
  /** Additional notes about the company */
  notes?: CompanyNotes;
  /** Unique identifier */
  id: number;
  /** Creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at?: CompanyUpdatedAt;
}
