/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { CompanyCreateSiret } from './companyCreateSiret';
import type { CompanyCreateWebsite } from './companyCreateWebsite';
import type { CompanyCreateHeadquarters } from './companyCreateHeadquarters';
import type { CompanyCreateCompanyType } from './companyCreateCompanyType';
import type { CompanyCreateIndustry } from './companyCreateIndustry';
import type { CompanyCreateNotes } from './companyCreateNotes';

/**
 * Schema for creating a new company (POST).
 */
export interface CompanyCreate {
  /**
   * Company name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** French business ID (SIRET) */
  siret?: CompanyCreateSiret;
  /** Company website URL */
  website?: CompanyCreateWebsite;
  /** Company headquarters address */
  headquarters?: CompanyCreateHeadquarters;
  /** Whether this company is an intermediary (ESN, agency) */
  is_intermediary?: boolean;
  /** Type: ESN, startup, enterprise, SME, etc. */
  company_type?: CompanyCreateCompanyType;
  /** Industry: Healthcare, automotive, etc. */
  industry?: CompanyCreateIndustry;
  /** Additional notes about the company */
  notes?: CompanyCreateNotes;
}
