/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ContactUpdateLastName } from './contactUpdateLastName';
import type { ContactUpdateFirstName } from './contactUpdateFirstName';
import type { ContactUpdatePosition } from './contactUpdatePosition';
import type { ContactUpdateEmail } from './contactUpdateEmail';
import type { ContactUpdatePhone } from './contactUpdatePhone';
import type { ContactUpdateLinkedin } from './contactUpdateLinkedin';
import type { ContactUpdateRelationshipNotes } from './contactUpdateRelationshipNotes';
import type { ContactUpdateIsIndependentRecruiter } from './contactUpdateIsIndependentRecruiter';
import type { ContactUpdateNotes } from './contactUpdateNotes';
import type { ContactUpdateCompanyId } from './contactUpdateCompanyId';

/**
 * Schema for updating a contact (PUT/PATCH).
All fields are optional to support partial updates.
 */
export interface ContactUpdate {
  last_name?: ContactUpdateLastName;
  first_name?: ContactUpdateFirstName;
  position?: ContactUpdatePosition;
  email?: ContactUpdateEmail;
  phone?: ContactUpdatePhone;
  linkedin?: ContactUpdateLinkedin;
  relationship_notes?: ContactUpdateRelationshipNotes;
  is_independent_recruiter?: ContactUpdateIsIndependentRecruiter;
  notes?: ContactUpdateNotes;
  company_id?: ContactUpdateCompanyId;
}
