/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of employment contract.
 */
export type ContractType = typeof ContractType[keyof typeof ContractType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContractType = {
  permanent: 'permanent',
  fixed_term: 'fixed_term',
  freelance: 'freelance',
  contractor: 'contractor',
  internship: 'internship',
  apprenticeship: 'apprenticeship',
} as const;
