/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ContactPosition } from './contactPosition';
import type { ContactEmail } from './contactEmail';
import type { ContactPhone } from './contactPhone';
import type { ContactLinkedin } from './contactLinkedin';
import type { ContactRelationshipNotes } from './contactRelationshipNotes';
import type { ContactNotes } from './contactNotes';
import type { ContactCompanyId } from './contactCompanyId';
import type { ContactUpdatedAt } from './contactUpdatedAt';

/**
 * Schema for reading a contact (GET).
Includes all fields including generated ones (id, timestamps).
 */
export interface Contact {
  /**
   * Contact's last name
   * @minLength 1
   * @maxLength 100
   */
  last_name: string;
  /**
   * Contact's first name
   * @minLength 1
   * @maxLength 100
   */
  first_name: string;
  /** Job title/position */
  position?: ContactPosition;
  /** Email address */
  email?: ContactEmail;
  /** Phone number (will be normalized to E.164) */
  phone?: ContactPhone;
  /** LinkedIn profile URL (normalized to short format) */
  linkedin?: ContactLinkedin;
  /** How you know this person */
  relationship_notes?: ContactRelationshipNotes;
  /** Whether this is an independent recruiter */
  is_independent_recruiter?: boolean;
  /** Additional notes */
  notes?: ContactNotes;
  /** Associated company ID */
  company_id?: ContactCompanyId;
  /** Unique identifier */
  id: number;
  /** Creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at?: ContactUpdatedAt;
}
