/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ContactCreatePosition } from './contactCreatePosition';
import type { ContactCreateEmail } from './contactCreateEmail';
import type { ContactCreatePhone } from './contactCreatePhone';
import type { ContactCreateLinkedin } from './contactCreateLinkedin';
import type { ContactCreateRelationshipNotes } from './contactCreateRelationshipNotes';
import type { ContactCreateNotes } from './contactCreateNotes';
import type { ContactCreateCompanyId } from './contactCreateCompanyId';

/**
 * Schema for creating a new contact (POST).
 */
export interface ContactCreate {
  /**
   * Contact's last name
   * @minLength 1
   * @maxLength 100
   */
  last_name: string;
  /**
   * Contact's first name
   * @minLength 1
   * @maxLength 100
   */
  first_name: string;
  /** Job title/position */
  position?: ContactCreatePosition;
  /** Email address */
  email?: ContactCreateEmail;
  /** Phone number (will be normalized to E.164) */
  phone?: ContactCreatePhone;
  /** LinkedIn profile URL (normalized to short format) */
  linkedin?: ContactCreateLinkedin;
  /** How you know this person */
  relationship_notes?: ContactCreateRelationshipNotes;
  /** Whether this is an independent recruiter */
  is_independent_recruiter?: boolean;
  /** Additional notes */
  notes?: ContactCreateNotes;
  /** Associated company ID */
  company_id?: ContactCreateCompanyId;
}
