/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { Application } from './application';
import type { Opportunity } from './opportunity';
import type { Company } from './company';
import type { Contact } from './contact';

export type DocumentAssociationEntity = Application | Opportunity | Company | Contact | null;
