/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentFormat } from './documentFormat';
import type { DocumentDescription } from './documentDescription';

/**
 * Schema for reading a document (GET).

Includes all fields including generated ones (id, timestamp).
 */
export interface Document {
  /**
   * Document name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * Document type: resume, cover_letter, portfolio, certificate, job_posting, other
   * @minLength 1
   * @maxLength 50
   */
  type: string;
  /** File format: pdf, docx, jpg, external, etc. */
  format: DocumentFormat;
  /**
   * Storage path (local) or URL (external)
   * @minLength 1
   */
  path: string;
  /** Free text description */
  description?: DocumentDescription;
  /** Whether document is an external link */
  is_external?: boolean;
  /** Unique identifier */
  id: number;
  /** Owner user ID */
  owner_id: number;
  /** Creation timestamp */
  created_at: string;
}
