/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { EntityType } from './entityType';

/**
 * Schema for reading a document association (GET).
Includes all fields including generated ones (id, created_at).
 */
export interface DocumentAssociation {
  /**
   * ID of the document
   */
  document_id: number;
  /** Type of the associated entity (application, opportunity, etc.) */
  entity_type: EntityType;
  /**
   * ID of the associated entity
   */
  entity_id: number;
  /** Unique identifier */
  id: number;
  /** Creation timestamp */
  created_at: string;
}
