/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentUpdateName } from './documentUpdateName';
import type { DocumentUpdateType } from './documentUpdateType';
import type { DocumentUpdateDescription } from './documentUpdateDescription';
import type { DocumentUpdatePath } from './documentUpdatePath';
import type { DocumentUpdateIsExternal } from './documentUpdateIsExternal';

/**
 * Schema for updating a document (PUT/PATCH).

All fields are optional to support partial updates.

**Special Cases:**
- **path + is_external**: Can be updated together to change storage location
  (e.g., local file → external link, or update external URL)
- **format**: Automatically set to 'external' when is_external=true

**Notes:**
- When changing from local to external, the local file will be deleted
- When changing external URL, old URL remains accessible (not controlled by CandiDash)
- Cannot change from external to local via PUT (use dedicated upload endpoint instead)
 */
export interface DocumentUpdate {
  name?: DocumentUpdateName;
  type?: DocumentUpdateType;
  description?: DocumentUpdateDescription;
  /** New path (URL for external, or leave unchanged) */
  path?: DocumentUpdatePath;
  /** Change storage type (local ↔ external) */
  is_external?: DocumentUpdateIsExternal;
}
