/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Change storage type (local ↔ external)
 */
export type DocumentUpdateIsExternal = boolean | null;
