/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Entity types that can have associated documents.
 */
export type EntityType = typeof EntityType[keyof typeof EntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntityType = {
  application: 'application',
  opportunity: 'opportunity',
  company: 'company',
  contact: 'contact',
} as const;
