/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

export type GetActionsApiV1ActionsGetParams = {
/**
 * Number of records to skip
 * @minimum 0
 */
skip?: number;
/**
 * Maximum number of records to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Filter by application ID
 */
application_id?: number | null;
/**
 * Filter by completion status (true=completed_date IS NOT NULL)
 */
completed?: boolean | null;
};
