/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ApplicationStatus } from './applicationStatus';

export type GetApplicationsApiV1ApplicationsGetParams = {
/**
 * Number of records to skip
 * @minimum 0
 */
skip?: number;
/**
 * Maximum number of records to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Filter by opportunity ID
 */
opportunity_id?: number | null;
/**
 * Filter by application status
 */
status?: ApplicationStatus | null;
/**
 * Filter by archive status
 */
is_archived?: boolean | null;
};
