/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

export type GetContactsApiV1ContactsGetParams = {
/**
 * Number of records to skip
 * @minimum 0
 */
skip?: number;
/**
 * Maximum number of records to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Filter by company ID
 */
company_id?: number | null;
/**
 * Filter by independent recruiter status
 */
is_independent_recruiter?: boolean | null;
};
