/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { EntityType } from './entityType';

export type GetDocumentAssociationsApiV1DocumentAssociationsGetParams = {
/**
 * Number of records to skip
 * @minimum 0
 */
skip?: number;
/**
 * Maximum number of records to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Filter by document ID
 */
document_id?: number | null;
/**
 * Filter by entity type
 */
entity_type?: EntityType | null;
/**
 * Filter by entity ID (requires entity_type)
 */
entity_id?: number | null;
};
