/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ApplicationType } from './applicationType';
import type { ContractType } from './contractType';

export type GetOpportunitiesApiV1OpportunitiesGetParams = {
/**
 * Number of records to skip
 * @minimum 0
 */
skip?: number;
/**
 * Maximum number of records to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Filter by company ID
 */
company_id?: number | null;
/**
 * Filter by application type
 */
application_type?: ApplicationType | null;
/**
 * Filter by contract type
 */
contract_type?: ContractType | null;
};
