/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { EventStatus } from './eventStatus';

export type GetScheduledEventsApiV1ScheduledEventsGetParams = {
/**
 * Number of records to skip
 * @minimum 0
 */
skip?: number;
/**
 * Maximum number of records to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Filter by event status
 */
status?: EventStatus | null;
};
