/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for reading an opportunity-product association (GET).
Includes all fields including generated ones (id, timestamps).
 */
export interface OpportunityProduct {
  /**
   * ID of the opportunity
   */
  opportunity_id: number;
  /**
   * ID of the product
   */
  product_id: number;
  /** Unique identifier */
  id: number;
  /** Creation timestamp */
  created_at: string;
}
