/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * How this contact is related (e.g. direct approach, referral)
 */
export type OpportunityContactCreateOrigin = string | null;
