/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { OpportunityUpdateJobTitle } from './opportunityUpdateJobTitle';
import type { OpportunityUpdateApplicationType } from './opportunityUpdateApplicationType';
import type { OpportunityUpdateCompanyId } from './opportunityUpdateCompanyId';
import type { OpportunityUpdatePositionType } from './opportunityUpdatePositionType';
import type { OpportunityUpdateContractType } from './opportunityUpdateContractType';
import type { OpportunityUpdateLocation } from './opportunityUpdateLocation';
import type { OpportunityUpdateJobPostingUrl } from './opportunityUpdateJobPostingUrl';
import type { OpportunityUpdateJobDescription } from './opportunityUpdateJobDescription';
import type { OpportunityUpdateRequiredSkills } from './opportunityUpdateRequiredSkills';
import type { OpportunityUpdateTechnologies } from './opportunityUpdateTechnologies';
import type { OpportunityUpdateSalaryMin } from './opportunityUpdateSalaryMin';
import type { OpportunityUpdateSalaryMax } from './opportunityUpdateSalaryMax';
import type { OpportunityUpdateSalaryInfo } from './opportunityUpdateSalaryInfo';
import type { OpportunityUpdateRemotePolicy } from './opportunityUpdateRemotePolicy';
import type { OpportunityUpdateRemoteDetails } from './opportunityUpdateRemoteDetails';
import type { OpportunityUpdateSource } from './opportunityUpdateSource';
import type { OpportunityUpdateRecruitmentProcess } from './opportunityUpdateRecruitmentProcess';

/**
 * Schema for updating an opportunity (PUT/PATCH).
All fields are optional to support partial updates.
 */
export interface OpportunityUpdate {
  job_title?: OpportunityUpdateJobTitle;
  application_type?: OpportunityUpdateApplicationType;
  company_id?: OpportunityUpdateCompanyId;
  position_type?: OpportunityUpdatePositionType;
  contract_type?: OpportunityUpdateContractType;
  location?: OpportunityUpdateLocation;
  job_posting_url?: OpportunityUpdateJobPostingUrl;
  job_description?: OpportunityUpdateJobDescription;
  required_skills?: OpportunityUpdateRequiredSkills;
  technologies?: OpportunityUpdateTechnologies;
  salary_min?: OpportunityUpdateSalaryMin;
  salary_max?: OpportunityUpdateSalaryMax;
  salary_info?: OpportunityUpdateSalaryInfo;
  remote_policy?: OpportunityUpdateRemotePolicy;
  remote_details?: OpportunityUpdateRemoteDetails;
  source?: OpportunityUpdateSource;
  recruitment_process?: OpportunityUpdateRecruitmentProcess;
}
