/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { OpportunityContactUpdateIsPrimaryContact } from './opportunityContactUpdateIsPrimaryContact';
import type { OpportunityContactUpdateContactRole } from './opportunityContactUpdateContactRole';
import type { OpportunityContactUpdateOrigin } from './opportunityContactUpdateOrigin';
import type { OpportunityContactUpdateNotes } from './opportunityContactUpdateNotes';

/**
 * Schema for updating an opportunity-contact association (PUT/PATCH).
Only metadata fields can be updated. Foreign keys are immutable.
All fields are optional to support partial updates.
 */
export interface OpportunityContactUpdate {
  is_primary_contact?: OpportunityContactUpdateIsPrimaryContact;
  contact_role?: OpportunityContactUpdateContactRole;
  origin?: OpportunityContactUpdateOrigin;
  notes?: OpportunityContactUpdateNotes;
}
