/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { OpportunityContactCreateContactRole } from './opportunityContactCreateContactRole';
import type { OpportunityContactCreateOrigin } from './opportunityContactCreateOrigin';
import type { OpportunityContactCreateNotes } from './opportunityContactCreateNotes';

/**
 * Schema for creating a new opportunity-contact association (POST).
 */
export interface OpportunityContactCreate {
  /**
   * ID of the opportunity
   */
  opportunity_id: number;
  /**
   * ID of the contact
   */
  contact_id: number;
  /** Whether this is the primary contact for this opportunity */
  is_primary_contact?: boolean;
  /** Role of the contact in this specific opportunity (e.g. Recruiter, Hiring Manager) */
  contact_role?: OpportunityContactCreateContactRole;
  /** How this contact is related (e.g. direct approach, referral) */
  origin?: OpportunityContactCreateOrigin;
  /** Contextual notes for this association */
  notes?: OpportunityContactCreateNotes;
}
