/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for creating a new opportunity-product association (POST).
 */
export interface OpportunityProductCreate {
  /**
   * ID of the opportunity
   */
  opportunity_id: number;
  /**
   * ID of the product
   */
  product_id: number;
}
