/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ApplicationType } from './applicationType';
import type { OpportunityCreateCompanyId } from './opportunityCreateCompanyId';
import type { OpportunityCreatePositionType } from './opportunityCreatePositionType';
import type { OpportunityCreateContractType } from './opportunityCreateContractType';
import type { OpportunityCreateLocation } from './opportunityCreateLocation';
import type { OpportunityCreateJobPostingUrl } from './opportunityCreateJobPostingUrl';
import type { OpportunityCreateJobDescription } from './opportunityCreateJobDescription';
import type { OpportunityCreateRequiredSkills } from './opportunityCreateRequiredSkills';
import type { OpportunityCreateTechnologies } from './opportunityCreateTechnologies';
import type { OpportunityCreateSalaryMin } from './opportunityCreateSalaryMin';
import type { OpportunityCreateSalaryMax } from './opportunityCreateSalaryMax';
import type { OpportunityCreateSalaryInfo } from './opportunityCreateSalaryInfo';
import type { OpportunityCreateRemotePolicy } from './opportunityCreateRemotePolicy';
import type { OpportunityCreateRemoteDetails } from './opportunityCreateRemoteDetails';
import type { OpportunityCreateSource } from './opportunityCreateSource';
import type { OpportunityCreateRecruitmentProcess } from './opportunityCreateRecruitmentProcess';

/**
 * Schema for creating a new opportunity (POST).
 */
export interface OpportunityCreate {
  /**
   * Job title
   * @minLength 2
   * @maxLength 255
   */
  job_title: string;
  /** Type of application (posting, spontaneous, etc.) */
  application_type: ApplicationType;
  /** Associated company ID */
  company_id?: OpportunityCreateCompanyId;
  /** Role type (backend, frontend, etc.) */
  position_type?: OpportunityCreatePositionType;
  /** Type of employment contract */
  contract_type?: OpportunityCreateContractType;
  /** City, Country or specific location */
  location?: OpportunityCreateLocation;
  /** Link to original job posting */
  job_posting_url?: OpportunityCreateJobPostingUrl;
  /** Summary or full text of the job description */
  job_description?: OpportunityCreateJobDescription;
  /** List of required skills */
  required_skills?: OpportunityCreateRequiredSkills;
  /** Tech stack mentioned */
  technologies?: OpportunityCreateTechnologies;
  /** Minimum salary offered */
  salary_min?: OpportunityCreateSalaryMin;
  /** Maximum salary offered */
  salary_max?: OpportunityCreateSalaryMax;
  /** Additional salary details (benefits, equity, etc.) */
  salary_info?: OpportunityCreateSalaryInfo;
  /** Remote work policy */
  remote_policy?: OpportunityCreateRemotePolicy;
  /** Specific details about remote policy */
  remote_details?: OpportunityCreateRemoteDetails;
  /** Source of the opportunity (LinkedIn, Indeed, etc.) */
  source?: OpportunityCreateSource;
  /** Notes on the recruitment process steps */
  recruitment_process?: OpportunityCreateRecruitmentProcess;
}
