/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { OpportunityContactContactRole } from './opportunityContactContactRole';
import type { OpportunityContactOrigin } from './opportunityContactOrigin';
import type { OpportunityContactNotes } from './opportunityContactNotes';
import type { OpportunityContactOpportunity } from './opportunityContactOpportunity';
import type { OpportunityContactContact } from './opportunityContactContact';

/**
 * Schema for reading an opportunity-contact association (GET).
Includes all fields including generated ones (id, timestamps).
 */
export interface OpportunityContact {
  /**
   * ID of the opportunity
   */
  opportunity_id: number;
  /**
   * ID of the contact
   */
  contact_id: number;
  /** Whether this is the primary contact for this opportunity */
  is_primary_contact?: boolean;
  /** Role of the contact in this specific opportunity (e.g. Recruiter, Hiring Manager) */
  contact_role?: OpportunityContactContactRole;
  /** How this contact is related (e.g. direct approach, referral) */
  origin?: OpportunityContactOrigin;
  /** Contextual notes for this association */
  notes?: OpportunityContactNotes;
  /** Unique identifier */
  id: number;
  /** Creation timestamp */
  created_at: string;
  opportunity?: OpportunityContactOpportunity;
  contact?: OpportunityContactContact;
}
