/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Role of the contact in this specific opportunity (e.g. Recruiter, Hiring Manager)
 */
export type OpportunityContactCreateContactRole = string | null;
