/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Source of the opportunity (LinkedIn, Indeed, etc.)
 */
export type OpportunityCreateSource = string | null;
