/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ContractType } from './contractType';

/**
 * Type of employment contract
 */
export type OpportunityContractType = ContractType | null;
