/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ApplicationType } from './applicationType';
import type { OpportunityCompanyId } from './opportunityCompanyId';
import type { OpportunityPositionType } from './opportunityPositionType';
import type { OpportunityContractType } from './opportunityContractType';
import type { OpportunityLocation } from './opportunityLocation';
import type { OpportunityJobPostingUrl } from './opportunityJobPostingUrl';
import type { OpportunityJobDescription } from './opportunityJobDescription';
import type { OpportunityRequiredSkills } from './opportunityRequiredSkills';
import type { OpportunityTechnologies } from './opportunityTechnologies';
import type { OpportunitySalaryMin } from './opportunitySalaryMin';
import type { OpportunitySalaryMax } from './opportunitySalaryMax';
import type { OpportunitySalaryInfo } from './opportunitySalaryInfo';
import type { OpportunityRemotePolicy } from './opportunityRemotePolicy';
import type { OpportunityRemoteDetails } from './opportunityRemoteDetails';
import type { OpportunitySource } from './opportunitySource';
import type { OpportunityRecruitmentProcess } from './opportunityRecruitmentProcess';
import type { OpportunityUpdatedAt } from './opportunityUpdatedAt';
import type { OpportunityCompany } from './opportunityCompany';

/**
 * Schema for reading an opportunity (GET).
Includes all fields including generated ones (id, timestamps).
 */
export interface Opportunity {
  /**
   * Job title
   * @minLength 2
   * @maxLength 255
   */
  job_title: string;
  /** Type of application (posting, spontaneous, etc.) */
  application_type: ApplicationType;
  /** Associated company ID */
  company_id?: OpportunityCompanyId;
  /** Role type (backend, frontend, etc.) */
  position_type?: OpportunityPositionType;
  /** Type of employment contract */
  contract_type?: OpportunityContractType;
  /** City, Country or specific location */
  location?: OpportunityLocation;
  /** Link to original job posting */
  job_posting_url?: OpportunityJobPostingUrl;
  /** Summary or full text of the job description */
  job_description?: OpportunityJobDescription;
  /** List of required skills */
  required_skills?: OpportunityRequiredSkills;
  /** Tech stack mentioned */
  technologies?: OpportunityTechnologies;
  /** Minimum salary offered */
  salary_min?: OpportunitySalaryMin;
  /** Maximum salary offered */
  salary_max?: OpportunitySalaryMax;
  /** Additional salary details (benefits, equity, etc.) */
  salary_info?: OpportunitySalaryInfo;
  /** Remote work policy */
  remote_policy?: OpportunityRemotePolicy;
  /** Specific details about remote policy */
  remote_details?: OpportunityRemoteDetails;
  /** Source of the opportunity (LinkedIn, Indeed, etc.) */
  source?: OpportunitySource;
  /** Notes on the recruitment process steps */
  recruitment_process?: OpportunityRecruitmentProcess;
  /** Unique identifier */
  id: number;
  /** Creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at?: OpportunityUpdatedAt;
  company?: OpportunityCompany;
}
