/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ProductUpdateName } from './productUpdateName';
import type { ProductUpdateDescription } from './productUpdateDescription';
import type { ProductUpdateCompanyId } from './productUpdateCompanyId';
import type { ProductUpdateWebsite } from './productUpdateWebsite';
import type { ProductUpdateTechnologiesUsed } from './productUpdateTechnologiesUsed';

/**
 * Schema for updating a product (PUT/PATCH).
All fields are optional to support partial updates.
 */
export interface ProductUpdate {
  name?: ProductUpdateName;
  description?: ProductUpdateDescription;
  company_id?: ProductUpdateCompanyId;
  website?: ProductUpdateWebsite;
  technologies_used?: ProductUpdateTechnologiesUsed;
}
