/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ProductCreateDescription } from './productCreateDescription';
import type { ProductCreateWebsite } from './productCreateWebsite';
import type { ProductCreateTechnologiesUsed } from './productCreateTechnologiesUsed';

/**
 * Schema for creating a new product (POST).
 */
export interface ProductCreate {
  /**
   * Product or service name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** Detailed description of the product */
  description?: ProductCreateDescription;
  /**
   * Associated company ID
   */
  company_id: number;
  /** Product specific website URL */
  website?: ProductCreateWebsite;
  /** Stack or technologies used in this product */
  technologies_used?: ProductCreateTechnologiesUsed;
}
