/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ProductDescription } from './productDescription';
import type { ProductWebsite } from './productWebsite';
import type { ProductTechnologiesUsed } from './productTechnologiesUsed';
import type { ProductCompany } from './productCompany';

/**
 * Schema for reading a product (GET).
Includes all fields including generated ones (id, timestamps).
 */
export interface Product {
  /**
   * Product or service name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** Detailed description of the product */
  description?: ProductDescription;
  /**
   * Associated company ID
   */
  company_id: number;
  /** Product specific website URL */
  website?: ProductWebsite;
  /** Stack or technologies used in this product */
  technologies_used?: ProductTechnologiesUsed;
  /** Unique identifier */
  id: number;
  /** Creation timestamp */
  created_at: string;
  company?: ProductCompany;
}
