/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Remote work policy.
 */
export type RemotePolicy = typeof RemotePolicy[keyof typeof RemotePolicy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RemotePolicy = {
  on_site: 'on_site',
  full_remote: 'full_remote',
  hybrid: 'hybrid',
  flexible: 'flexible',
} as const;
