/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * URL for video call or meeting details
 */
export type ScheduledEventCreateEventLink = string | null;
