/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ScheduledEventUpdateTitle } from './scheduledEventUpdateTitle';
import type { ScheduledEventUpdateEventType } from './scheduledEventUpdateEventType';
import type { ScheduledEventUpdateScheduledDate } from './scheduledEventUpdateScheduledDate';
import type { ScheduledEventUpdateDurationMinutes } from './scheduledEventUpdateDurationMinutes';
import type { ScheduledEventUpdateCommunicationMethod } from './scheduledEventUpdateCommunicationMethod';
import type { ScheduledEventUpdateEventLink } from './scheduledEventUpdateEventLink';
import type { ScheduledEventUpdatePhoneNumber } from './scheduledEventUpdatePhoneNumber';
import type { ScheduledEventUpdateLocation } from './scheduledEventUpdateLocation';
import type { ScheduledEventUpdateInstructions } from './scheduledEventUpdateInstructions';
import type { ScheduledEventUpdateStatus } from './scheduledEventUpdateStatus';
import type { ScheduledEventUpdateNotes } from './scheduledEventUpdateNotes';

/**
 * Schema for updating a scheduled event (PUT/PATCH).
All fields are optional to support partial updates.
 */
export interface ScheduledEventUpdate {
  title?: ScheduledEventUpdateTitle;
  event_type?: ScheduledEventUpdateEventType;
  scheduled_date?: ScheduledEventUpdateScheduledDate;
  duration_minutes?: ScheduledEventUpdateDurationMinutes;
  communication_method?: ScheduledEventUpdateCommunicationMethod;
  event_link?: ScheduledEventUpdateEventLink;
  phone_number?: ScheduledEventUpdatePhoneNumber;
  location?: ScheduledEventUpdateLocation;
  instructions?: ScheduledEventUpdateInstructions;
  status?: ScheduledEventUpdateStatus;
  notes?: ScheduledEventUpdateNotes;
}
