/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ScheduledEventEventType } from './scheduledEventEventType';
import type { ScheduledEventDurationMinutes } from './scheduledEventDurationMinutes';
import type { ScheduledEventCommunicationMethod } from './scheduledEventCommunicationMethod';
import type { ScheduledEventEventLink } from './scheduledEventEventLink';
import type { ScheduledEventPhoneNumber } from './scheduledEventPhoneNumber';
import type { ScheduledEventLocation } from './scheduledEventLocation';
import type { ScheduledEventInstructions } from './scheduledEventInstructions';
import type { EventStatus } from './eventStatus';
import type { ScheduledEventNotes } from './scheduledEventNotes';
import type { ScheduledEventUpdatedAt } from './scheduledEventUpdatedAt';

/**
 * Schema for reading a scheduled event (GET).
Includes all fields including generated ones (id, timestamps).
 */
export interface ScheduledEvent {
  /**
   * Event title (e.g., 'HR Interview')
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  /** Type of event (interview, call, meeting) */
  event_type?: ScheduledEventEventType;
  /** Date and time of the event */
  scheduled_date: string;
  /** Duration in minutes */
  duration_minutes?: ScheduledEventDurationMinutes;
  /** Method (video, phone, etc.) */
  communication_method?: ScheduledEventCommunicationMethod;
  /** URL for video call or meeting details */
  event_link?: ScheduledEventEventLink;
  /** Phone number if applicable */
  phone_number?: ScheduledEventPhoneNumber;
  /** Physical address or location info */
  location?: ScheduledEventLocation;
  /** Specific instructions for the candidate */
  instructions?: ScheduledEventInstructions;
  /** Current status of the event */
  status?: EventStatus;
  /** Private notes about the event */
  notes?: ScheduledEventNotes;
  /** Unique identifier */
  id: number;
  /** Creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at?: ScheduledEventUpdatedAt;
}
