/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { ScheduledEventCreateEventType } from './scheduledEventCreateEventType';
import type { ScheduledEventCreateDurationMinutes } from './scheduledEventCreateDurationMinutes';
import type { ScheduledEventCreateCommunicationMethod } from './scheduledEventCreateCommunicationMethod';
import type { ScheduledEventCreateEventLink } from './scheduledEventCreateEventLink';
import type { ScheduledEventCreatePhoneNumber } from './scheduledEventCreatePhoneNumber';
import type { ScheduledEventCreateLocation } from './scheduledEventCreateLocation';
import type { ScheduledEventCreateInstructions } from './scheduledEventCreateInstructions';
import type { EventStatus } from './eventStatus';
import type { ScheduledEventCreateNotes } from './scheduledEventCreateNotes';

/**
 * Schema for creating a new scheduled event (POST).
 */
export interface ScheduledEventCreate {
  /**
   * Event title (e.g., 'HR Interview')
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  /** Type of event (interview, call, meeting) */
  event_type?: ScheduledEventCreateEventType;
  /** Date and time of the event */
  scheduled_date: string;
  /** Duration in minutes */
  duration_minutes?: ScheduledEventCreateDurationMinutes;
  /** Method (video, phone, etc.) */
  communication_method?: ScheduledEventCreateCommunicationMethod;
  /** URL for video call or meeting details */
  event_link?: ScheduledEventCreateEventLink;
  /** Phone number if applicable */
  phone_number?: ScheduledEventCreatePhoneNumber;
  /** Physical address or location info */
  location?: ScheduledEventCreateLocation;
  /** Specific instructions for the candidate */
  instructions?: ScheduledEventCreateInstructions;
  /** Current status of the event */
  status?: EventStatus;
  /** Private notes about the event */
  notes?: ScheduledEventCreateNotes;
}
