/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Token response schema.

Returned after successful login or token refresh.
Contains the access token (short lived).
 */
export interface Token {
  access_token: string;
  token_type?: string;
}
