/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { UserCreateFirstName } from './userCreateFirstName';
import type { UserCreateLastName } from './userCreateLastName';

/**
 * Schema for creating a new user (POST /auth/register).
Includes password confirmation validation.
 */
export interface UserCreate {
  /** User email address (unique) */
  email: string;
  /** User first name */
  first_name?: UserCreateFirstName;
  /** User last name */
  last_name?: UserCreateLastName;
  /**
   * User password (minimum 8 characters)
   * @minLength 8
   */
  password: string;
  /**
   * Password confirmation
   * @minLength 8
   */
  confirm_password: string;
}
