/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import type { UserFirstName } from './userFirstName';
import type { UserLastName } from './userLastName';
import type { UserUpdatedAt } from './userUpdatedAt';

/**
 * Schema for reading a user (GET).
Includes all fields except password (never exposed).
 */
export interface User {
  /** User email address (unique) */
  email: string;
  /** User first name */
  first_name?: UserFirstName;
  /** User last name */
  last_name?: UserLastName;
  /** Unique identifier */
  id: number;
  /** Whether the user account is active */
  is_active: boolean;
  /** Creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at?: UserUpdatedAt;
}
