/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetProductsApiV1ProductsGetParams,
  HTTPValidationError,
  Product,
  ProductCreate,
  ProductUpdate
} from '.././model';

import { customInstance } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a list of products owned by the current user with pagination and optional filtering.

- **skip**: Number of records to skip (for pagination)
- **limit**: Maximum number of records to return (max 100)
- **company_id**: Optional filter by company ID

Returns only products belonging to the authenticated user.
 * @summary Get Products
 */
export const getProductsApiV1ProductsGet = (
    params?: GetProductsApiV1ProductsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Product[]>(
      {url: `/api/v1/products/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetProductsApiV1ProductsGetQueryKey = (params?: GetProductsApiV1ProductsGetParams,) => {
    return [
    `/api/v1/products/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetProductsApiV1ProductsGetQueryOptions = <TData = Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>, TError = HTTPValidationError>(params?: GetProductsApiV1ProductsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductsApiV1ProductsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>> = ({ signal }) => getProductsApiV1ProductsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductsApiV1ProductsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>>
export type GetProductsApiV1ProductsGetQueryError = HTTPValidationError


export function useGetProductsApiV1ProductsGet<TData = Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetProductsApiV1ProductsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>,
          TError,
          Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductsApiV1ProductsGet<TData = Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>, TError = HTTPValidationError>(
 params?: GetProductsApiV1ProductsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>,
          TError,
          Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductsApiV1ProductsGet<TData = Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>, TError = HTTPValidationError>(
 params?: GetProductsApiV1ProductsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Products
 */

export function useGetProductsApiV1ProductsGet<TData = Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>, TError = HTTPValidationError>(
 params?: GetProductsApiV1ProductsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsApiV1ProductsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductsApiV1ProductsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new product.

- **name**: Product or service name (required)
- **description**: Detailed description (optional)
- **company_id**: Associated company ID (required)
- **website**: Product specific website URL (optional)
- **technologies_used**: Stack or technologies used (optional)

The product will be automatically assigned to the authenticated user.
 * @summary Create Product
 */
export const createProductApiV1ProductsPost = (
    productCreate: ProductCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Product>(
      {url: `/api/v1/products/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: productCreate, signal
    },
      options);
    }
  


export const getCreateProductApiV1ProductsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProductApiV1ProductsPost>>, TError,{data: ProductCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createProductApiV1ProductsPost>>, TError,{data: ProductCreate}, TContext> => {

const mutationKey = ['createProductApiV1ProductsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProductApiV1ProductsPost>>, {data: ProductCreate}> = (props) => {
          const {data} = props ?? {};

          return  createProductApiV1ProductsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProductApiV1ProductsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createProductApiV1ProductsPost>>>
    export type CreateProductApiV1ProductsPostMutationBody = ProductCreate
    export type CreateProductApiV1ProductsPostMutationError = HTTPValidationError

    /**
 * @summary Create Product
 */
export const useCreateProductApiV1ProductsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProductApiV1ProductsPost>>, TError,{data: ProductCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProductApiV1ProductsPost>>,
        TError,
        {data: ProductCreate},
        TContext
      > => {

      const mutationOptions = getCreateProductApiV1ProductsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a specific product by ID.

- **product_id**: The ID of the product to retrieve

Returns 404 if product doesn't exist or doesn't belong to the authenticated user.
 * @summary Get Product
 */
export const getProductApiV1ProductsProductIdGet = (
    productId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Product>(
      {url: `/api/v1/products/${productId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetProductApiV1ProductsProductIdGetQueryKey = (productId?: number,) => {
    return [
    `/api/v1/products/${productId}`
    ] as const;
    }

    
export const getGetProductApiV1ProductsProductIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>, TError = HTTPValidationError>(productId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductApiV1ProductsProductIdGetQueryKey(productId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>> = ({ signal }) => getProductApiV1ProductsProductIdGet(productId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(productId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductApiV1ProductsProductIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>>
export type GetProductApiV1ProductsProductIdGetQueryError = HTTPValidationError


export function useGetProductApiV1ProductsProductIdGet<TData = Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>, TError = HTTPValidationError>(
 productId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>,
          TError,
          Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductApiV1ProductsProductIdGet<TData = Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>, TError = HTTPValidationError>(
 productId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>,
          TError,
          Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductApiV1ProductsProductIdGet<TData = Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>, TError = HTTPValidationError>(
 productId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Product
 */

export function useGetProductApiV1ProductsProductIdGet<TData = Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>, TError = HTTPValidationError>(
 productId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductApiV1ProductsProductIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductApiV1ProductsProductIdGetQueryOptions(productId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing product.

- **product_id**: The ID of the product to update
- All fields are optional - only provided fields will be updated

Returns 404 if product doesn't exist or doesn't belong to the authenticated user.
 * @summary Update Product
 */
export const updateProductApiV1ProductsProductIdPut = (
    productId: number,
    productUpdate: ProductUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Product>(
      {url: `/api/v1/products/${productId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: productUpdate
    },
      options);
    }
  


export const getUpdateProductApiV1ProductsProductIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProductApiV1ProductsProductIdPut>>, TError,{productId: number;data: ProductUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProductApiV1ProductsProductIdPut>>, TError,{productId: number;data: ProductUpdate}, TContext> => {

const mutationKey = ['updateProductApiV1ProductsProductIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProductApiV1ProductsProductIdPut>>, {productId: number;data: ProductUpdate}> = (props) => {
          const {productId,data} = props ?? {};

          return  updateProductApiV1ProductsProductIdPut(productId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProductApiV1ProductsProductIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateProductApiV1ProductsProductIdPut>>>
    export type UpdateProductApiV1ProductsProductIdPutMutationBody = ProductUpdate
    export type UpdateProductApiV1ProductsProductIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Product
 */
export const useUpdateProductApiV1ProductsProductIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProductApiV1ProductsProductIdPut>>, TError,{productId: number;data: ProductUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProductApiV1ProductsProductIdPut>>,
        TError,
        {productId: number;data: ProductUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateProductApiV1ProductsProductIdPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a product.

- **product_id**: The ID of the product to delete

Returns 404 if product doesn't exist or doesn't belong to the authenticated user.
 * @summary Delete Product
 */
export const deleteProductApiV1ProductsProductIdDelete = (
    productId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/products/${productId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteProductApiV1ProductsProductIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProductApiV1ProductsProductIdDelete>>, TError,{productId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProductApiV1ProductsProductIdDelete>>, TError,{productId: number}, TContext> => {

const mutationKey = ['deleteProductApiV1ProductsProductIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProductApiV1ProductsProductIdDelete>>, {productId: number}> = (props) => {
          const {productId} = props ?? {};

          return  deleteProductApiV1ProductsProductIdDelete(productId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductApiV1ProductsProductIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProductApiV1ProductsProductIdDelete>>>
    
    export type DeleteProductApiV1ProductsProductIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Product
 */
export const useDeleteProductApiV1ProductsProductIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProductApiV1ProductsProductIdDelete>>, TError,{productId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProductApiV1ProductsProductIdDelete>>,
        TError,
        {productId: number},
        TContext
      > => {

      const mutationOptions = getDeleteProductApiV1ProductsProductIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    