"""feat(models/product): add owner_id direct

Revision ID: 8cb804c5cb60
Revises: 18761baeb254
Create Date: 2025-12-05 16:24:12.959352+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb804c5cb60'
down_revision: Union[str, None] = '18761baeb254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_owner_id'), 'products', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'products', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.execute("""
        UPDATE products
        SET owner_id = companies.owner_id
        FROM companies
        WHERE products.company_id = companies.id
    """)
    op.alter_column('products', 'owner_id', nullable=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_owner_id'), table_name='products')
    op.drop_column('products', 'owner_id')
    # ### end Alembic commands ###
