"""add indexes to opportunity_product foreign keys

Revision ID: 62437d614efc
Revises: 207363832c1b
Create Date: 2025-12-08 13:29:33.771969+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62437d614efc'
down_revision: Union[str, None] = '207363832c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_opportunity_products_opportunity_id'), 'opportunity_products', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_products_product_id'), 'opportunity_products', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_products_product_id'), table_name='opportunity_products')
    op.drop_index(op.f('ix_opportunity_products_opportunity_id'), table_name='opportunity_products')
    # ### end Alembic commands ###
