"""add indexes to opportunity_contact foreign keys

Revision ID: b420970e2706
Revises: 62437d614efc
Create Date: 2025-12-08 13:58:15.291593+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b420970e2706'
down_revision: Union[str, None] = '62437d614efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_opportunity_contacts_contact_id'), 'opportunity_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_opportunity_contacts_opportunity_id'), 'opportunity_contacts', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_contacts_opportunity_id'), table_name='opportunity_contacts')
    op.drop_index(op.f('ix_opportunity_contacts_contact_id'), table_name='opportunity_contacts')
    # ### end Alembic commands ###
