"""refactor(models): change company siret to partial unique index with owner_id

Revision ID: af8306b863c8
Revises: 9de6f767800b
Create Date: 2025-12-04 11:48:09.786408+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8306b863c8'
down_revision: Union[str, None] = '9de6f767800b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_siret_key', 'companies', type_='unique')
    op.create_index('ix_company_siret_owner_unique', 'companies', ['siret', 'owner_id'], unique=True, postgresql_where=sa.text('siret IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_siret_owner_unique', table_name='companies', postgresql_where=sa.text('siret IS NOT NULL'))
    op.create_unique_constraint('companies_siret_key', 'companies', ['siret'])
    # ### end Alembic commands ###
