"""make opportunity position_type and contract_type nullable

Revision ID: 0ae8a2d8c582
Revises: f238adbcb7d0
Create Date: 2025-12-02 23:17:22.984122+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ae8a2d8c582'
down_revision: Union[str, None] = 'f238adbcb7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunities', 'position_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('opportunities', 'contract_type',
               existing_type=postgresql.ENUM('PERMANENT', 'FIXED_TERM', 'FREELANCE', 'CONTRACTOR', 'INTERNSHIP', 'APPRENTICESHIP', name='contracttype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunities', 'contract_type',
               existing_type=postgresql.ENUM('PERMANENT', 'FIXED_TERM', 'FREELANCE', 'CONTRACTOR', 'INTERNSHIP', 'APPRENTICESHIP', name='contracttype'),
               nullable=False)
    op.alter_column('opportunities', 'position_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
