"""refactor(models/action): add owner_id, remove parent_action_id+is_completed

Revision ID: e0fb99d7da63
Revises: af8306b863c8
Create Date: 2025-12-05 13:06:32.351615+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0fb99d7da63'
down_revision: Union[str, None] = 'af8306b863c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_actions_owner_id'), 'actions', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'actions', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.execute("""
        UPDATE actions
        SET owner_id = opportunities.owner_id
        FROM applications
        JOIN opportunities ON applications.opportunity_id = opportunities.id
        WHERE actions.application_id = applications.id
    """)
    op.alter_column('actions', 'owner_id', nullable=False)
    op.drop_constraint('actions_parent_action_id_fkey', 'actions', type_='foreignkey')
    op.drop_column('actions', 'parent_action_id')
    op.drop_column('actions', 'is_completed')
    op.add_column('actions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.false(), nullable=False))
    op.add_column('actions', sa.Column('parent_action_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('actions_parent_action_id_fkey', 'actions', 'actions', ['parent_action_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_actions_owner_id'), table_name='actions')
    op.drop_column('actions', 'owner_id')
    op.drop_column('actions', 'updated_at')
    # ### end Alembic commands ###
