"""add created_at to opportunity_product

Revision ID: 207363832c1b
Revises: 8cb804c5cb60
Create Date: 2025-12-08 13:06:15.462052+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207363832c1b'
down_revision: Union[str, None] = '8cb804c5cb60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_products', 'created_at')
    # ### end Alembic commands ###
