"""add owner_id to opportunities table for multi-tenancy

Revision ID: 0a0e68e903f0
Revises: 92a4634a9d0c
Create Date: 2025-12-03 00:09:02.538169+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0e68e903f0'
down_revision: Union[str, None] = '92a4634a9d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_opportunities_owner_id'), 'opportunities', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'opportunities', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_index(op.f('ix_opportunities_owner_id'), table_name='opportunities')
    op.drop_column('opportunities', 'owner_id')
    # ### end Alembic commands ###
