"""add owner_id to companies table for multi-tenancy

Revision ID: 92a4634a9d0c
Revises: 0ae8a2d8c582
Create Date: 2025-12-02 23:56:13.397493+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a4634a9d0c'
down_revision: Union[str, None] = '0ae8a2d8c582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_companies_owner_id'), 'companies', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'companies', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_owner_id'), table_name='companies')
    op.drop_column('companies', 'owner_id')
    # ### end Alembic commands ###
