"""feat(models/application): add owner_id direct

Revision ID: 18761baeb254
Revises: e0fb99d7da63
Create Date: 2025-12-05 15:30:37.047907+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18761baeb254'
down_revision: Union[str, None] = 'e0fb99d7da63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_applications_owner_id'), 'applications', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'applications', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.execute("""
        UPDATE applications
        SET owner_id = opportunities.owner_id
        FROM opportunities
        WHERE applications.opportunity_id = opportunities.id
    """)
    op.alter_column('applications', 'owner_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_owner_id'), table_name='applications')
    op.drop_column('applications', 'owner_id')
    # ### end Alembic commands ###
