"""add indexes to document_association

Revision ID: 7f9204270414
Revises: b420970e2706
Create Date: 2025-12-08 14:13:27.913490+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9204270414'
down_revision: Union[str, None] = 'b420970e2706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_associations_document_id'), 'document_associations', ['document_id'], unique=False)
    op.create_index('ix_document_associations_entity', 'document_associations', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_associations_entity', table_name='document_associations')
    op.drop_index(op.f('ix_document_associations_document_id'), table_name='document_associations')
    # ### end Alembic commands ###
