"""add owner_id to scheduled_events table for multi-tenancy

Revision ID: 9de6f767800b
Revises: 0f350a71a725
Create Date: 2025-12-03 00:19:49.780270+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de6f767800b'
down_revision: Union[str, None] = '0f350a71a725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_events', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_scheduled_events_owner_id'), 'scheduled_events', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'scheduled_events', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_events', type_='foreignkey')
    op.drop_index(op.f('ix_scheduled_events_owner_id'), table_name='scheduled_events')
    op.drop_column('scheduled_events', 'owner_id')
    # ### end Alembic commands ###
