/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetScheduledEventsApiV1ScheduledEventsGetParams,
  HTTPValidationError,
  ScheduledEvent,
  ScheduledEventCreate,
  ScheduledEventUpdate
} from '.././model';

import { customInstance } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a list of scheduled events owned by the current user with pagination and optional filtering.

- **skip**: Number of records to skip (for pagination)
- **limit**: Maximum number of records to return (max 100)
- **status**: Optional filter by event status (pending, confirmed, etc.)

Returns only scheduled events belonging to the authenticated user.
 * @summary Get Scheduled Events
 */
export const getScheduledEventsApiV1ScheduledEventsGet = (
    params?: GetScheduledEventsApiV1ScheduledEventsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ScheduledEvent[]>(
      {url: `/api/v1/scheduled-events/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetScheduledEventsApiV1ScheduledEventsGetQueryKey = (params?: GetScheduledEventsApiV1ScheduledEventsGetParams,) => {
    return [
    `/api/v1/scheduled-events/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetScheduledEventsApiV1ScheduledEventsGetQueryOptions = <TData = Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>, TError = HTTPValidationError>(params?: GetScheduledEventsApiV1ScheduledEventsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetScheduledEventsApiV1ScheduledEventsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>> = ({ signal }) => getScheduledEventsApiV1ScheduledEventsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetScheduledEventsApiV1ScheduledEventsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>>
export type GetScheduledEventsApiV1ScheduledEventsGetQueryError = HTTPValidationError


export function useGetScheduledEventsApiV1ScheduledEventsGet<TData = Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetScheduledEventsApiV1ScheduledEventsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>,
          TError,
          Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetScheduledEventsApiV1ScheduledEventsGet<TData = Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>, TError = HTTPValidationError>(
 params?: GetScheduledEventsApiV1ScheduledEventsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>,
          TError,
          Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetScheduledEventsApiV1ScheduledEventsGet<TData = Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>, TError = HTTPValidationError>(
 params?: GetScheduledEventsApiV1ScheduledEventsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Scheduled Events
 */

export function useGetScheduledEventsApiV1ScheduledEventsGet<TData = Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>, TError = HTTPValidationError>(
 params?: GetScheduledEventsApiV1ScheduledEventsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduledEventsApiV1ScheduledEventsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetScheduledEventsApiV1ScheduledEventsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new scheduled event.

- **title**: Event title (required)
- **scheduled_date**: Date and time (required)
- **status**: Status (default: pending)
- ... and other optional details

The scheduled event will be automatically assigned to the authenticated user.
 * @summary Create Scheduled Event
 */
export const createScheduledEventApiV1ScheduledEventsPost = (
    scheduledEventCreate: ScheduledEventCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ScheduledEvent>(
      {url: `/api/v1/scheduled-events/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: scheduledEventCreate, signal
    },
      options);
    }
  


export const getCreateScheduledEventApiV1ScheduledEventsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createScheduledEventApiV1ScheduledEventsPost>>, TError,{data: ScheduledEventCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createScheduledEventApiV1ScheduledEventsPost>>, TError,{data: ScheduledEventCreate}, TContext> => {

const mutationKey = ['createScheduledEventApiV1ScheduledEventsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createScheduledEventApiV1ScheduledEventsPost>>, {data: ScheduledEventCreate}> = (props) => {
          const {data} = props ?? {};

          return  createScheduledEventApiV1ScheduledEventsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateScheduledEventApiV1ScheduledEventsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createScheduledEventApiV1ScheduledEventsPost>>>
    export type CreateScheduledEventApiV1ScheduledEventsPostMutationBody = ScheduledEventCreate
    export type CreateScheduledEventApiV1ScheduledEventsPostMutationError = HTTPValidationError

    /**
 * @summary Create Scheduled Event
 */
export const useCreateScheduledEventApiV1ScheduledEventsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createScheduledEventApiV1ScheduledEventsPost>>, TError,{data: ScheduledEventCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createScheduledEventApiV1ScheduledEventsPost>>,
        TError,
        {data: ScheduledEventCreate},
        TContext
      > => {

      const mutationOptions = getCreateScheduledEventApiV1ScheduledEventsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a specific scheduled event by ID.

- **event_id**: The ID of the event to retrieve

Returns 404 if event doesn't exist or doesn't belong to the authenticated user.
 * @summary Get Scheduled Event
 */
export const getScheduledEventApiV1ScheduledEventsEventIdGet = (
    eventId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ScheduledEvent>(
      {url: `/api/v1/scheduled-events/${eventId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetScheduledEventApiV1ScheduledEventsEventIdGetQueryKey = (eventId?: number,) => {
    return [
    `/api/v1/scheduled-events/${eventId}`
    ] as const;
    }

    
export const getGetScheduledEventApiV1ScheduledEventsEventIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>, TError = HTTPValidationError>(eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetScheduledEventApiV1ScheduledEventsEventIdGetQueryKey(eventId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>> = ({ signal }) => getScheduledEventApiV1ScheduledEventsEventIdGet(eventId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(eventId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetScheduledEventApiV1ScheduledEventsEventIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>>
export type GetScheduledEventApiV1ScheduledEventsEventIdGetQueryError = HTTPValidationError


export function useGetScheduledEventApiV1ScheduledEventsEventIdGet<TData = Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>, TError = HTTPValidationError>(
 eventId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>,
          TError,
          Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetScheduledEventApiV1ScheduledEventsEventIdGet<TData = Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>, TError = HTTPValidationError>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>,
          TError,
          Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetScheduledEventApiV1ScheduledEventsEventIdGet<TData = Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>, TError = HTTPValidationError>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Scheduled Event
 */

export function useGetScheduledEventApiV1ScheduledEventsEventIdGet<TData = Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>, TError = HTTPValidationError>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduledEventApiV1ScheduledEventsEventIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetScheduledEventApiV1ScheduledEventsEventIdGetQueryOptions(eventId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update an existing scheduled event.

- **event_id**: The ID of the event to update
- All fields are optional

Returns 404 if event doesn't exist or doesn't belong to the authenticated user.
 * @summary Update Scheduled Event
 */
export const updateScheduledEventApiV1ScheduledEventsEventIdPut = (
    eventId: number,
    scheduledEventUpdate: ScheduledEventUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ScheduledEvent>(
      {url: `/api/v1/scheduled-events/${eventId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: scheduledEventUpdate
    },
      options);
    }
  


export const getUpdateScheduledEventApiV1ScheduledEventsEventIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateScheduledEventApiV1ScheduledEventsEventIdPut>>, TError,{eventId: number;data: ScheduledEventUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateScheduledEventApiV1ScheduledEventsEventIdPut>>, TError,{eventId: number;data: ScheduledEventUpdate}, TContext> => {

const mutationKey = ['updateScheduledEventApiV1ScheduledEventsEventIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateScheduledEventApiV1ScheduledEventsEventIdPut>>, {eventId: number;data: ScheduledEventUpdate}> = (props) => {
          const {eventId,data} = props ?? {};

          return  updateScheduledEventApiV1ScheduledEventsEventIdPut(eventId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateScheduledEventApiV1ScheduledEventsEventIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateScheduledEventApiV1ScheduledEventsEventIdPut>>>
    export type UpdateScheduledEventApiV1ScheduledEventsEventIdPutMutationBody = ScheduledEventUpdate
    export type UpdateScheduledEventApiV1ScheduledEventsEventIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Scheduled Event
 */
export const useUpdateScheduledEventApiV1ScheduledEventsEventIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateScheduledEventApiV1ScheduledEventsEventIdPut>>, TError,{eventId: number;data: ScheduledEventUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateScheduledEventApiV1ScheduledEventsEventIdPut>>,
        TError,
        {eventId: number;data: ScheduledEventUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateScheduledEventApiV1ScheduledEventsEventIdPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a scheduled event.

- **event_id**: The ID of the event to delete

Returns 404 if event doesn't exist or doesn't belong to the authenticated user.
 * @summary Delete Scheduled Event
 */
export const deleteScheduledEventApiV1ScheduledEventsEventIdDelete = (
    eventId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/scheduled-events/${eventId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteScheduledEventApiV1ScheduledEventsEventIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteScheduledEventApiV1ScheduledEventsEventIdDelete>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteScheduledEventApiV1ScheduledEventsEventIdDelete>>, TError,{eventId: number}, TContext> => {

const mutationKey = ['deleteScheduledEventApiV1ScheduledEventsEventIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteScheduledEventApiV1ScheduledEventsEventIdDelete>>, {eventId: number}> = (props) => {
          const {eventId} = props ?? {};

          return  deleteScheduledEventApiV1ScheduledEventsEventIdDelete(eventId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteScheduledEventApiV1ScheduledEventsEventIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteScheduledEventApiV1ScheduledEventsEventIdDelete>>>
    
    export type DeleteScheduledEventApiV1ScheduledEventsEventIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Scheduled Event
 */
export const useDeleteScheduledEventApiV1ScheduledEventsEventIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteScheduledEventApiV1ScheduledEventsEventIdDelete>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteScheduledEventApiV1ScheduledEventsEventIdDelete>>,
        TError,
        {eventId: number},
        TContext
      > => {

      const mutationOptions = getDeleteScheduledEventApiV1ScheduledEventsEventIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    