/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * CandiDash API
 * Job application tracking system API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetOpportunityProductsApiV1OpportunityProductsGetParams,
  HTTPValidationError,
  OpportunityProduct,
  OpportunityProductCreate
} from '.././model';

import { customInstance } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a list of opportunity-product associations owned by the current user with pagination and filtering.

- **skip**: Number of records to skip (for pagination)
- **limit**: Maximum number of records to return (max 100)
- **opportunity_id**: Optional filter by opportunity ID
- **product_id**: Optional filter by product ID

Returns only associations where the opportunity belongs to the authenticated user.
 * @summary Get Opportunity Products
 */
export const getOpportunityProductsApiV1OpportunityProductsGet = (
    params?: GetOpportunityProductsApiV1OpportunityProductsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OpportunityProduct[]>(
      {url: `/api/v1/opportunity-products/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetOpportunityProductsApiV1OpportunityProductsGetQueryKey = (params?: GetOpportunityProductsApiV1OpportunityProductsGetParams,) => {
    return [
    `/api/v1/opportunity-products/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetOpportunityProductsApiV1OpportunityProductsGetQueryOptions = <TData = Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>, TError = HTTPValidationError>(params?: GetOpportunityProductsApiV1OpportunityProductsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOpportunityProductsApiV1OpportunityProductsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>> = ({ signal }) => getOpportunityProductsApiV1OpportunityProductsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOpportunityProductsApiV1OpportunityProductsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>>
export type GetOpportunityProductsApiV1OpportunityProductsGetQueryError = HTTPValidationError


export function useGetOpportunityProductsApiV1OpportunityProductsGet<TData = Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetOpportunityProductsApiV1OpportunityProductsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>,
          TError,
          Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpportunityProductsApiV1OpportunityProductsGet<TData = Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>, TError = HTTPValidationError>(
 params?: GetOpportunityProductsApiV1OpportunityProductsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>,
          TError,
          Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpportunityProductsApiV1OpportunityProductsGet<TData = Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>, TError = HTTPValidationError>(
 params?: GetOpportunityProductsApiV1OpportunityProductsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Opportunity Products
 */

export function useGetOpportunityProductsApiV1OpportunityProductsGet<TData = Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>, TError = HTTPValidationError>(
 params?: GetOpportunityProductsApiV1OpportunityProductsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityProductsApiV1OpportunityProductsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOpportunityProductsApiV1OpportunityProductsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new link between an opportunity and a product.

- **opportunity_id**: ID of the opportunity (required)
- **product_id**: ID of the product (required)

Both opportunity and product must belong to the authenticated user.
The association will be timestamped automatically.
 * @summary Create Opportunity Product
 */
export const createOpportunityProductApiV1OpportunityProductsPost = (
    opportunityProductCreate: OpportunityProductCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OpportunityProduct>(
      {url: `/api/v1/opportunity-products/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: opportunityProductCreate, signal
    },
      options);
    }
  


export const getCreateOpportunityProductApiV1OpportunityProductsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOpportunityProductApiV1OpportunityProductsPost>>, TError,{data: OpportunityProductCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createOpportunityProductApiV1OpportunityProductsPost>>, TError,{data: OpportunityProductCreate}, TContext> => {

const mutationKey = ['createOpportunityProductApiV1OpportunityProductsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOpportunityProductApiV1OpportunityProductsPost>>, {data: OpportunityProductCreate}> = (props) => {
          const {data} = props ?? {};

          return  createOpportunityProductApiV1OpportunityProductsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOpportunityProductApiV1OpportunityProductsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createOpportunityProductApiV1OpportunityProductsPost>>>
    export type CreateOpportunityProductApiV1OpportunityProductsPostMutationBody = OpportunityProductCreate
    export type CreateOpportunityProductApiV1OpportunityProductsPostMutationError = HTTPValidationError

    /**
 * @summary Create Opportunity Product
 */
export const useCreateOpportunityProductApiV1OpportunityProductsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOpportunityProductApiV1OpportunityProductsPost>>, TError,{data: OpportunityProductCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOpportunityProductApiV1OpportunityProductsPost>>,
        TError,
        {data: OpportunityProductCreate},
        TContext
      > => {

      const mutationOptions = getCreateOpportunityProductApiV1OpportunityProductsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a specific opportunity-product association by ID.

- **association_id**: The ID of the association to retrieve

Returns 404 if association doesn't exist or doesn't belong to the authenticated user.
 * @summary Get Opportunity Product
 */
export const getOpportunityProductApiV1OpportunityProductsAssociationIdGet = (
    associationId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OpportunityProduct>(
      {url: `/api/v1/opportunity-products/${associationId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetOpportunityProductApiV1OpportunityProductsAssociationIdGetQueryKey = (associationId?: number,) => {
    return [
    `/api/v1/opportunity-products/${associationId}`
    ] as const;
    }

    
export const getGetOpportunityProductApiV1OpportunityProductsAssociationIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>, TError = HTTPValidationError>(associationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOpportunityProductApiV1OpportunityProductsAssociationIdGetQueryKey(associationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>> = ({ signal }) => getOpportunityProductApiV1OpportunityProductsAssociationIdGet(associationId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(associationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOpportunityProductApiV1OpportunityProductsAssociationIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>>
export type GetOpportunityProductApiV1OpportunityProductsAssociationIdGetQueryError = HTTPValidationError


export function useGetOpportunityProductApiV1OpportunityProductsAssociationIdGet<TData = Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>, TError = HTTPValidationError>(
 associationId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>,
          TError,
          Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpportunityProductApiV1OpportunityProductsAssociationIdGet<TData = Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>, TError = HTTPValidationError>(
 associationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>,
          TError,
          Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpportunityProductApiV1OpportunityProductsAssociationIdGet<TData = Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>, TError = HTTPValidationError>(
 associationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Opportunity Product
 */

export function useGetOpportunityProductApiV1OpportunityProductsAssociationIdGet<TData = Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>, TError = HTTPValidationError>(
 associationId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpportunityProductApiV1OpportunityProductsAssociationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOpportunityProductApiV1OpportunityProductsAssociationIdGetQueryOptions(associationId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Delete an opportunity-product association.

- **association_id**: The ID of the association to delete

Returns 404 if association doesn't exist or doesn't belong to the authenticated user.
 * @summary Delete Opportunity Product
 */
export const deleteOpportunityProductApiV1OpportunityProductsAssociationIdDelete = (
    associationId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/opportunity-products/${associationId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteOpportunityProductApiV1OpportunityProductsAssociationIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOpportunityProductApiV1OpportunityProductsAssociationIdDelete>>, TError,{associationId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOpportunityProductApiV1OpportunityProductsAssociationIdDelete>>, TError,{associationId: number}, TContext> => {

const mutationKey = ['deleteOpportunityProductApiV1OpportunityProductsAssociationIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOpportunityProductApiV1OpportunityProductsAssociationIdDelete>>, {associationId: number}> = (props) => {
          const {associationId} = props ?? {};

          return  deleteOpportunityProductApiV1OpportunityProductsAssociationIdDelete(associationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOpportunityProductApiV1OpportunityProductsAssociationIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOpportunityProductApiV1OpportunityProductsAssociationIdDelete>>>
    
    export type DeleteOpportunityProductApiV1OpportunityProductsAssociationIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Opportunity Product
 */
export const useDeleteOpportunityProductApiV1OpportunityProductsAssociationIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOpportunityProductApiV1OpportunityProductsAssociationIdDelete>>, TError,{associationId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOpportunityProductApiV1OpportunityProductsAssociationIdDelete>>,
        TError,
        {associationId: number},
        TContext
      > => {

      const mutationOptions = getDeleteOpportunityProductApiV1OpportunityProductsAssociationIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    